//! Sheet copy for languages that ship a full chrome table.
//! Languages without a row fall back to English via `i18n::phrase`.

pub fn row(lang: &str) -> Option<&'static [(&'static str, &'static str)]> {
    Some(match lang {
        "pt" => PT,
        "it" => IT,
        "nl" => NL,
        "pl" => PL,
        "uk" => UK,
        "ru" => RU,
        "fa" => FA,
        "tr" => TR,
        "ja" => JA,
        "ko" => KO,
        "vi" => VI,
        "th" => TH,
        "id" => ID,
        "sw" => SW,
        "bn" => BN,
        "as" => AS,
        "brx" => BRX,
        "doi" => DOI,
        "gu" => GU,
        "kn" => KN,
        "ks" => KS,
        "kok" => KOK,
        "ml" => ML,
        "mni" => MNI,
        "mr" => MR,
        "mai" => MAI,
        "ne" => NE,
        "or" => OR,
        "pa" => PA,
        "sa" => SA,
        "sat" => SAT,
        "sd" => SD,
        "ta" => TA,
        "te" => TE,
        "ur" => UR,
        "bho" => BHO,
        "hne" => HNE,
        "lus" => LUS,
        "kha" => KHA,
        "grt" => GRT,
        "trp" => TRP,
        "lep" => LEP,
        _ => return None,
    })
}

const PT: &[(&str, &str)] = &[
    ("remove", "Remover"),
    ("share", "Partilhar convite"),
    ("paste", "Colar convite"),
    ("paste_body", "Cole uma ligação ghalbol:// ou https://ghalbol.com/connect/."),
    ("add", "Adicionar pela chave pública"),
    ("add_body", "O convidado guarda a chave pública do anfitrião. O anfitrião não precisa da sua primeiro."),
    ("contacts", "Contactos"),
    ("none", "Ainda não há contactos"),
    ("blocked", "Bloqueados"),
    ("blocked_empty", "Nenhum contacto bloqueado. Cole uma chave pública para bloquear alguém da lista."),
    ("delivery", "Armazenamento de entrega"),
    ("log", "Registo da aplicação"),
    ("key", "Chave privada"),
    ("key_body", "Escreva a palavra-passe e depois mostre a chave. Faça-o só num sítio privado."),
    ("backup", "Exportar cópia"),
    ("backup_body", "Guarda o cofre cifrado. Continua a precisar da palavra-passe para o abrir noutro aparelho."),
    ("password", "Alterar palavra-passe"),
    ("password_body", "Palavra-passe atual no campo do convite. A nova no campo do nome. Cópias antigas mantêm a palavra-passe antiga."),
    ("about", "Sobre o Ghal Bol"),
    ("about_body", "Mensageiro com cifra de ponta a ponta. Cada aparelho guarda a sua conversa."),
    ("no_status", "Sem estado"),
    ("save_backup", "Guarde a cópia"),
    ("save_backup_body", "Guarde a cópia cifrada antes de conversar. Esta identidade não se recupera sem ela e a palavra-passe."),
    ("back", "Voltar"),
    ("join_go", "Entrar"),
    ("add_go", "Adicionar contacto"),
    ("add_short", "Adicionar"),
    ("toggle", "Alternar bloqueio"),
    ("refresh", "Atualizar"),
    ("show_key", "Mostrar chave"),
    ("save", "Guardar cópia"),
    ("change", "Alterar palavra-passe"),
    ("save_status", "Guardar estado"),
    ("speaker", "Altifalante"),
    ("speaker_off", "Altifalante desligado"),
    ("scan_qr", "Ler QR"),
    ("qr_picture", "Imagem QR"),
    ("must_save", "Guarde a cópia antes de continuar."),
    ("enter_password", "Escreva primeiro a palavra-passe desta cópia."),
    ("choose_file", "Escolha um ficheiro de cópia do cofre."),
    ("added", "Contacto adicionado"),
    ("saved_prefix", "Guardado"),
];

const IT: &[(&str, &str)] = &[
    ("remove", "Rimuovi"),
    ("share", "Condividi invito"),
    ("paste", "Incolla invito"),
    ("paste_body", "Incolla un link ghalbol:// o https://ghalbol.com/connect/."),
    ("add", "Aggiungi con chiave pubblica"),
    ("add_body", "L’ospite salva la chiave pubblica dell’host. L’host non ha bisogno della tua prima."),
    ("contacts", "Contatti"),
    ("none", "Nessun contatto"),
    ("blocked", "Bloccati"),
    ("blocked_empty", "Nessun contatto bloccato. Incolla una chiave pubblica per bloccare qualcuno già in elenco."),
    ("delivery", "Archivio di consegna"),
    ("log", "Registro dell’app"),
    ("key", "Chiave privata"),
    ("key_body", "Scrivi la password dell’app e poi mostra la chiave. Fallo solo in un luogo privato."),
    ("backup", "Esporta copia"),
    ("backup_body", "Salva il portachiavi cifrato. Serve ancora la password per aprirlo su un altro dispositivo."),
    ("password", "Cambia password"),
    ("password_body", "Password attuale nel campo invito. Quella nuova nel campo nome. Le copie vecchie restano con la password vecchia."),
    ("about", "Informazioni su Ghal Bol"),
    ("about_body", "Messaggistica cifrata end-to-end. Ogni dispositivo tiene la propria conversazione."),
    ("no_status", "Nessuno stato"),
    ("save_backup", "Salva la copia"),
    ("save_backup_body", "Salva la copia cifrata prima di chattare. Questa identità non si recupera senza di essa e la password."),
    ("back", "Indietro"),
    ("join_go", "Entra"),
    ("add_go", "Aggiungi contatto"),
    ("add_short", "Aggiungi"),
    ("toggle", "Cambia blocco"),
    ("refresh", "Aggiorna"),
    ("show_key", "Mostra chiave"),
    ("save", "Salva copia"),
    ("change", "Cambia password"),
    ("save_status", "Salva stato"),
    ("speaker", "Altoparlante"),
    ("speaker_off", "Altoparlante spento"),
    ("scan_qr", "Scansiona QR"),
    ("qr_picture", "Immagine QR"),
    ("must_save", "Salva la copia prima di continuare."),
    ("enter_password", "Inserisci prima la password di questa copia."),
    ("choose_file", "Scegli un file di copia del portachiavi."),
    ("added", "Contatto aggiunto"),
    ("saved_prefix", "Salvato"),
];

const NL: &[(&str, &str)] = &[
    ("remove", "Verwijderen"),
    ("share", "Uitnodiging delen"),
    ("paste", "Uitnodiging plakken"),
    ("paste_body", "Plak een ghalbol://- of https://ghalbol.com/connect/-link."),
    ("add", "Toevoegen met publieke sleutel"),
    ("add_body", "De gast bewaart de publieke sleutel van de host. De host heeft die van jou niet eerst nodig."),
    ("contacts", "Contacten"),
    ("none", "Nog geen contacten"),
    ("blocked", "Geblokkeerd"),
    ("blocked_empty", "Geen geblokkeerde contacten. Plak een publieke sleutel om iemand uit de lijst te blokkeren."),
    ("delivery", "Afleveropslag"),
    ("log", "Applogboek"),
    ("key", "Privésleutel"),
    ("key_body", "Typ het app-wachtwoord en toon daarna de sleutel. Doe dit alleen op een privéplek."),
    ("backup", "Back-up exporteren"),
    ("backup_body", "Slaat de versleutelde sleutelkluis op. Je hebt het app-wachtwoord nog nodig op een ander apparaat."),
    ("password", "Wachtwoord wijzigen"),
    ("password_body", "Huidig wachtwoord in het uitnodigingsveld. Nieuw wachtwoord in het naamveld. Oude back-ups houden het oude wachtwoord."),
    ("about", "Over Ghal Bol"),
    ("about_body", "End-to-end versleutelde berichten. Elk apparaat bewaart zijn eigen gesprek."),
    ("no_status", "Geen status"),
    ("save_backup", "Bewaar de back-up"),
    ("save_backup_body", "Bewaar de versleutelde back-up voor je chat. Deze identiteit is zonder die en je wachtwoord niet terug te halen."),
    ("back", "Terug"),
    ("join_go", "Deelnemen"),
    ("add_go", "Contact toevoegen"),
    ("add_short", "Toevoegen"),
    ("toggle", "Blokkade wisselen"),
    ("refresh", "Verversen"),
    ("show_key", "Sleutel tonen"),
    ("save", "Back-up opslaan"),
    ("change", "Wachtwoord wijzigen"),
    ("save_status", "Status opslaan"),
    ("speaker", "Luidspreker"),
    ("speaker_off", "Luidspreker uit"),
    ("scan_qr", "QR scannen"),
    ("qr_picture", "QR-afbeelding"),
    ("must_save", "Bewaar de back-up voordat je verdergaat."),
    ("enter_password", "Typ eerst het wachtwoord van deze back-up."),
    ("choose_file", "Kies een back-upbestand van de sleutelkluis."),
    ("added", "Contact toegevoegd"),
    ("saved_prefix", "Opgeslagen"),
];

const PL: &[(&str, &str)] = &[
    ("remove", "Usuń"),
    ("share", "Udostępnij zaproszenie"),
    ("paste", "Wklej zaproszenie"),
    ("paste_body", "Wklej link ghalbol:// lub https://ghalbol.com/connect/."),
    ("add", "Dodaj kluczem publicznym"),
    ("add_body", "Gość zapisuje klucz publiczny gospodarza. Gospodarz nie potrzebuje twojego wcześniej."),
    ("contacts", "Kontakty"),
    ("none", "Brak kontaktów"),
    ("blocked", "Zablokowani"),
    ("blocked_empty", "Brak zablokowanych. Wklej klucz publiczny, aby zablokować kogoś z listy."),
    ("delivery", "Magazyn dostarczania"),
    ("log", "Dziennik aplikacji"),
    ("key", "Klucz prywatny"),
    ("key_body", "Wpisz hasło aplikacji, potem pokaż klucz. Rób to tylko w ustronnym miejscu."),
    ("backup", "Eksportuj kopię"),
    ("backup_body", "Zapisuje zaszyfrowany schowek kluczy. Do otwarcia na innym urządzeniu potrzebne jest hasło."),
    ("password", "Zmień hasło"),
    ("password_body", "Obecne hasło w polu zaproszenia. Nowe w polu nazwy. Starsze kopie zostają przy starym haśle."),
    ("about", "O Ghal Bol"),
    ("about_body", "Komunikator szyfrowany od końca do końca. Każde urządzenie trzyma własną rozmowę."),
    ("no_status", "Brak statusu"),
    ("save_backup", "Zapisz kopię"),
    ("save_backup_body", "Zapisz zaszyfrowaną kopię przed czatem. Tej tożsamości nie da się odzyskać bez niej i hasła."),
    ("back", "Wstecz"),
    ("join_go", "Dołącz"),
    ("add_go", "Dodaj kontakt"),
    ("add_short", "Dodaj"),
    ("toggle", "Przełącz blokadę"),
    ("refresh", "Odśwież"),
    ("show_key", "Pokaż klucz"),
    ("save", "Zapisz kopię"),
    ("change", "Zmień hasło"),
    ("save_status", "Zapisz status"),
    ("speaker", "Głośnik"),
    ("speaker_off", "Głośnik wyłączony"),
    ("scan_qr", "Skanuj QR"),
    ("qr_picture", "Obraz QR"),
    ("must_save", "Zapisz kopię, zanim przejdziesz dalej."),
    ("enter_password", "Najpierw wpisz hasło tej kopii."),
    ("choose_file", "Wybierz plik kopii schowka kluczy."),
    ("added", "Dodano kontakt"),
    ("saved_prefix", "Zapisano"),
];

const UK: &[(&str, &str)] = &[
    ("remove", "Видалити"),
    ("share", "Поділитися запрошенням"),
    ("paste", "Вставити запрошення"),
    ("paste_body", "Вставте посилання ghalbol:// або https://ghalbol.com/connect/."),
    ("add", "Додати за відкритим ключем"),
    ("add_body", "Гість зберігає відкритий ключ господаря. Господарю не потрібен ваш ключ наперед."),
    ("contacts", "Контакти"),
    ("none", "Контактів ще немає"),
    ("blocked", "Заблоковані"),
    ("blocked_empty", "Немає заблокованих. Вставте відкритий ключ, щоб заблокувати когось зі списку."),
    ("delivery", "Сховище доставки"),
    ("log", "Журнал застосунку"),
    ("key", "Приватний ключ"),
    ("key_body", "Введіть пароль застосунку, потім покажіть ключ. Робіть це лише наодинці."),
    ("backup", "Експорт копії"),
    ("backup_body", "Зберігає зашифроване сховище ключів. На іншому пристрої все одно потрібен пароль."),
    ("password", "Змінити пароль"),
    ("password_body", "Поточний пароль у полі запрошення. Новий — у полі імені. Старі копії лишаються зі старим паролем."),
    ("about", "Про Ghal Bol"),
    ("about_body", "Наскрізно зашифровані повідомлення. Кожен пристрій тримає власну розмову."),
    ("no_status", "Статус не задано"),
    ("save_backup", "Збережіть копію"),
    ("save_backup_body", "Збережіть зашифровану копію перед чатом. Цю особу не відновити без неї і пароля."),
    ("back", "Назад"),
    ("join_go", "Приєднатися"),
    ("add_go", "Додати контакт"),
    ("add_short", "Додати"),
    ("toggle", "Перемкнути блок"),
    ("refresh", "Оновити"),
    ("show_key", "Показати ключ"),
    ("save", "Зберегти копію"),
    ("change", "Змінити пароль"),
    ("save_status", "Зберегти статус"),
    ("speaker", "Гучномовець"),
    ("speaker_off", "Гучномовець вимкнено"),
    ("scan_qr", "Сканувати QR"),
    ("qr_picture", "Зображення QR"),
    ("must_save", "Збережіть копію, перш ніж продовжити."),
    ("enter_password", "Спочатку введіть пароль цієї копії."),
    ("choose_file", "Оберіть файл копії сховища ключів."),
    ("added", "Контакт додано"),
    ("saved_prefix", "Збережено"),
];

const RU: &[(&str, &str)] = &[
    ("remove", "Удалить"),
    ("share", "Поделиться приглашением"),
    ("paste", "Вставить приглашение"),
    ("paste_body", "Вставьте ссылку ghalbol:// или https://ghalbol.com/connect/."),
    ("add", "Добавить по открытому ключу"),
    ("add_body", "Гость хранит открытый ключ хозяина. Хозяину не нужен ваш ключ заранее."),
    ("contacts", "Контакты"),
    ("none", "Контактов пока нет"),
    ("blocked", "Заблокированные"),
    ("blocked_empty", "Нет заблокированных. Вставьте открытый ключ, чтобы заблокировать кого-то из списка."),
    ("delivery", "Хранилище доставки"),
    ("log", "Журнал приложения"),
    ("key", "Закрытый ключ"),
    ("key_body", "Введите пароль приложения, затем покажите ключ. Делайте это только наедине."),
    ("backup", "Экспорт копии"),
    ("backup_body", "Сохраняет зашифрованное хранилище ключей. На другом устройстве всё равно нужен пароль."),
    ("password", "Сменить пароль"),
    ("password_body", "Текущий пароль в поле приглашения. Новый — в поле имени. Старые копии остаются со старым паролем."),
    ("about", "О Ghal Bol"),
    ("about_body", "Сквозное шифрование сообщений. Каждое устройство хранит свою переписку."),
    ("no_status", "Статус не задан"),
    ("save_backup", "Сохраните копию"),
    ("save_backup_body", "Сохраните зашифрованную копию до чата. Эту личность нельзя восстановить без неё и пароля."),
    ("back", "Назад"),
    ("join_go", "Присоединиться"),
    ("add_go", "Добавить контакт"),
    ("add_short", "Добавить"),
    ("toggle", "Переключить блок"),
    ("refresh", "Обновить"),
    ("show_key", "Показать ключ"),
    ("save", "Сохранить копию"),
    ("change", "Сменить пароль"),
    ("save_status", "Сохранить статус"),
    ("speaker", "Динамик"),
    ("speaker_off", "Динамик выключен"),
    ("scan_qr", "Сканировать QR"),
    ("qr_picture", "Изображение QR"),
    ("must_save", "Сохраните копию, прежде чем продолжить."),
    ("enter_password", "Сначала введите пароль этой копии."),
    ("choose_file", "Выберите файл копии хранилища ключей."),
    ("added", "Контакт добавлен"),
    ("saved_prefix", "Сохранено"),
];

const FA: &[(&str, &str)] = &[
    ("remove", "حذف"),
    ("share", "هم‌رسانی دعوت"),
    ("paste", "چسباندن دعوت"),
    ("paste_body", "پیوند ghalbol:// یا https://ghalbol.com/connect/ را بچسبانید."),
    ("add", "افزودن با کلید عمومی"),
    ("add_body", "مهمان کلید عمومی میزبان را نگه می‌دارد. میزبان از پیش به کلید شما نیاز ندارد."),
    ("contacts", "مخاطبان"),
    ("none", "هنوز مخاطبی نیست"),
    ("blocked", "مسدودها"),
    ("blocked_empty", "مخاطب مسدودی نیست. برای مسدود کردن کسی از فهرست، کلید عمومی را بچسبانید."),
    ("delivery", "انبار تحویل"),
    ("log", "گزارش برنامه"),
    ("key", "کلید خصوصی"),
    ("key_body", "گذرواژه برنامه را بنویسید و سپس کلید را نشان دهید. فقط در جای خصوصی."),
    ("backup", "برون‌برد نسخه"),
    ("backup_body", "مخزن رمزشده کلید را ذخیره می‌کند. برای باز کردن در دستگاه دیگر همچنان گذرواژه لازم است."),
    ("password", "تغییر گذرواژه"),
    ("password_body", "گذرواژه فعلی در فیلد دعوت. گذرواژه تازه در فیلد نام. نسخه‌های قدیمی با گذرواژه قدیم می‌مانند."),
    ("about", "درباره غال بول"),
    ("about_body", "پیام‌رسان با رمزنگاری سرتاسری. هر دستگاه گفتگوی خودش را نگه می‌دارد."),
    ("no_status", "وضعیتی نیست"),
    ("save_backup", "نسخه را ذخیره کنید"),
    ("save_backup_body", "پیش از گفتگو نسخه رمزشده را ذخیره کنید. این هویت بدون آن و گذرواژه باز نمی‌گردد."),
    ("back", "بازگشت"),
    ("join_go", "پیوستن"),
    ("add_go", "افزودن مخاطب"),
    ("add_short", "افزودن"),
    ("toggle", "تغییر مسدودسازی"),
    ("refresh", "تازه‌سازی"),
    ("show_key", "نمایش کلید"),
    ("save", "ذخیره نسخه"),
    ("change", "تغییر گذرواژه"),
    ("save_status", "ذخیره وضعیت"),
    ("speaker", "بلندگو"),
    ("speaker_off", "بلندگو خاموش"),
    ("scan_qr", "اسکن QR"),
    ("qr_picture", "تصویر QR"),
    ("must_save", "پیش از ادامه نسخه را ذخیره کنید."),
    ("enter_password", "اول گذرواژه این نسخه را بنویسید."),
    ("choose_file", "پرونده نسخه مخزن کلید را انتخاب کنید."),
    ("added", "مخاطب افزوده شد"),
    ("saved_prefix", "ذخیره شد"),
];

const TR: &[(&str, &str)] = &[
    ("remove", "Kaldır"),
    ("share", "Daveti paylaş"),
    ("paste", "Daveti yapıştır"),
    ("paste_body", "Bir ghalbol:// veya https://ghalbol.com/connect/ bağlantısı yapıştırın."),
    ("add", "Açık anahtarla ekle"),
    ("add_body", "Konuk, ev sahibinin açık anahtarını saklar. Ev sahibi önce sizinkine ihtiyaç duymaz."),
    ("contacts", "Kişiler"),
    ("none", "Henüz kişi yok"),
    ("blocked", "Engellenenler"),
    ("blocked_empty", "Engelli kişi yok. Listedekini engellemek için açık anahtar yapıştırın."),
    ("delivery", "Teslim deposu"),
    ("log", "Uygulama günlüğü"),
    ("key", "Özel anahtar"),
    ("key_body", "Uygulama parolasını yazın, sonra anahtarı gösterin. Bunu yalnızca özel bir yerde yapın."),
    ("backup", "Yedeği dışa aktar"),
    ("backup_body", "Şifreli anahtar kasasını kaydeder. Başka cihazda açmak için parola yine gerekir."),
    ("password", "Parolayı değiştir"),
    ("password_body", "Geçerli parola davet alanına. Yeni parola ad alanına. Eski yedekler eski parolayı kullanır."),
    ("about", "Ghal Bol hakkında"),
    ("about_body", "Uçtan uca şifreli mesajlaşma. Her cihaz kendi konuşmasını tutar."),
    ("no_status", "Durum yok"),
    ("save_backup", "Yedeği kaydedin"),
    ("save_backup_body", "Sohbetten önce şifreli yedeği kaydedin. Bu kimlik yedek ve parola olmadan geri gelmez."),
    ("back", "Geri"),
    ("join_go", "Katıl"),
    ("add_go", "Kişi ekle"),
    ("add_short", "Ekle"),
    ("toggle", "Engeli değiştir"),
    ("refresh", "Yenile"),
    ("show_key", "Anahtarı göster"),
    ("save", "Yedeği kaydet"),
    ("change", "Parolayı değiştir"),
    ("save_status", "Durumu kaydet"),
    ("speaker", "Hoparlör"),
    ("speaker_off", "Hoparlör kapalı"),
    ("scan_qr", "QR tara"),
    ("qr_picture", "QR resmi"),
    ("must_save", "Devam etmeden önce yedeği kaydedin."),
    ("enter_password", "Önce bu yedeğin parolasını yazın."),
    ("choose_file", "Bir anahtar kasası yedek dosyası seçin."),
    ("added", "Kişi eklendi"),
    ("saved_prefix", "Kaydedildi"),
];

const JA: &[(&str, &str)] = &[
    ("remove", "削除"),
    ("share", "招待を共有"),
    ("paste", "招待を貼り付け"),
    ("paste_body", "ghalbol:// または https://ghalbol.com/connect/ のリンクを貼り付けます。"),
    ("add", "公開鍵で追加"),
    ("add_body", "客はホストの公開鍵を保存します。ホストは先にあなたの鍵を必要としません。"),
    ("contacts", "連絡先"),
    ("none", "連絡先はまだありません"),
    ("blocked", "ブロック中"),
    ("blocked_empty", "ブロックした連絡先はありません。一覧の相手を止めるには公開鍵を貼り付けます。"),
    ("delivery", "配送の保管"),
    ("log", "アプリの記録"),
    ("key", "秘密鍵"),
    ("key_body", "アプリのパスワードを入れてから鍵を表示します。人目のない場所だけで行ってください。"),
    ("backup", "バックアップを書き出す"),
    ("backup_body", "暗号化された鍵庫を保存します。別の機器で開くにはパスワードが必要です。"),
    ("password", "パスワードを変更"),
    ("password_body", "今のパスワードは招待欄へ。新しいパスワードは名前欄へ。古いバックアップは古いパスワードのままです。"),
    ("about", "Ghal Bol について"),
    ("about_body", "端から端まで暗号化したメッセージ。各機器が自分の会話だけを保持します。"),
    ("no_status", "状態なし"),
    ("save_backup", "バックアップを保存"),
    ("save_backup_body", "会話の前に暗号化したバックアップを保存してください。これとパスワードがなければこの身元は戻りません。"),
    ("back", "戻る"),
    ("join_go", "参加"),
    ("add_go", "連絡先を追加"),
    ("add_short", "追加"),
    ("toggle", "ブロックを切り替え"),
    ("refresh", "更新"),
    ("show_key", "鍵を表示"),
    ("save", "バックアップを保存"),
    ("change", "パスワードを変更"),
    ("save_status", "状態を保存"),
    ("speaker", "スピーカー"),
    ("speaker_off", "スピーカー切"),
    ("scan_qr", "QRを読む"),
    ("qr_picture", "QR画像"),
    ("must_save", "続ける前にバックアップを保存してください。"),
    ("enter_password", "先にこのバックアップのパスワードを入力してください。"),
    ("choose_file", "鍵庫のバックアップファイルを選んでください。"),
    ("added", "連絡先を追加しました"),
    ("saved_prefix", "保存しました"),
];

const KO: &[(&str, &str)] = &[
    ("remove", "삭제"),
    ("share", "초대 공유"),
    ("paste", "초대 붙여넣기"),
    ("paste_body", "ghalbol:// 또는 https://ghalbol.com/connect/ 링크를 붙여 넣으세요."),
    ("add", "공개 키로 추가"),
    ("add_body", "손님은 주인의 공개 키를 저장합니다. 주인은 먼저 당신의 키가 필요하지 않습니다."),
    ("contacts", "연락처"),
    ("none", "연락처가 없습니다"),
    ("blocked", "차단됨"),
    ("blocked_empty", "차단한 연락처가 없습니다. 목록의 사람을 막으려면 공개 키를 붙여 넣으세요."),
    ("delivery", "전달 보관"),
    ("log", "앱 기록"),
    ("key", "개인 키"),
    ("key_body", "앱 암호를 입력한 뒤 키를 표시하세요. 혼자 있는 곳에서만 하세요."),
    ("backup", "백업 내보내기"),
    ("backup_body", "암호화된 키 보관함을 저장합니다. 다른 기기에서 열려면 암호가 필요합니다."),
    ("password", "암호 변경"),
    ("password_body", "현재 암호는 초대 칸에. 새 암호는 이름 칸에. 이전 백업은 예전 암호를 씁니다."),
    ("about", "Ghal Bol 정보"),
    ("about_body", "끝에서 끝까지 암호화된 메시지. 각 기기가 자기 대화를 보관합니다."),
    ("no_status", "상태 없음"),
    ("save_backup", "백업을 저장하세요"),
    ("save_backup_body", "대화 전에 암호화된 백업을 저장하세요. 백업과 암호가 없으면 이 신원을 되돌릴 수 없습니다."),
    ("back", "뒤로"),
    ("join_go", "참여"),
    ("add_go", "연락처 추가"),
    ("add_short", "추가"),
    ("toggle", "차단 전환"),
    ("refresh", "새로고침"),
    ("show_key", "키 표시"),
    ("save", "백업 저장"),
    ("change", "암호 변경"),
    ("save_status", "상태 저장"),
    ("speaker", "스피커"),
    ("speaker_off", "스피커 끔"),
    ("scan_qr", "QR 스캔"),
    ("qr_picture", "QR 그림"),
    ("must_save", "계속하기 전에 백업을 저장하세요."),
    ("enter_password", "먼저 이 백업의 암호를 입력하세요."),
    ("choose_file", "키 보관함 백업 파일을 고르세요."),
    ("added", "연락처를 추가했습니다"),
    ("saved_prefix", "저장됨"),
];

const VI: &[(&str, &str)] = &[
    ("remove", "Xóa"),
    ("share", "Chia sẻ lời mời"),
    ("paste", "Dán lời mời"),
    ("paste_body", "Dán liên kết ghalbol:// hoặc https://ghalbol.com/connect/."),
    ("add", "Thêm bằng khóa công khai"),
    ("add_body", "Khách lưu khóa công khai của chủ. Chủ không cần khóa của bạn trước."),
    ("contacts", "Danh bạ"),
    ("none", "Chưa có danh bạ"),
    ("blocked", "Đã chặn"),
    ("blocked_empty", "Không có ai bị chặn. Dán khóa công khai để chặn người đã có trong danh sách."),
    ("delivery", "Kho chuyển tin"),
    ("log", "Nhật ký ứng dụng"),
    ("key", "Khóa riêng"),
    ("key_body", "Nhập mật khẩu ứng dụng rồi hiện khóa. Chỉ làm ở nơi riêng."),
    ("backup", "Xuất bản sao"),
    ("backup_body", "Lưu kho khóa đã mã hóa. Vẫn cần mật khẩu để mở trên máy khác."),
    ("password", "Đổi mật khẩu"),
    ("password_body", "Mật khẩu hiện tại ở ô lời mời. Mật khẩu mới ở ô tên. Bản sao cũ vẫn dùng mật khẩu cũ."),
    ("about", "Về Ghal Bol"),
    ("about_body", "Tin nhắn mã hóa đầu cuối. Mỗi máy giữ cuộc trò chuyện của mình."),
    ("no_status", "Chưa có trạng thái"),
    ("save_backup", "Hãy lưu bản sao"),
    ("save_backup_body", "Lưu bản sao đã mã hóa trước khi trò chuyện. Danh tính này không lấy lại được nếu thiếu bản sao và mật khẩu."),
    ("back", "Quay lại"),
    ("join_go", "Tham gia"),
    ("add_go", "Thêm liên hệ"),
    ("add_short", "Thêm"),
    ("toggle", "Đổi chặn"),
    ("refresh", "Làm mới"),
    ("show_key", "Hiện khóa"),
    ("save", "Lưu bản sao"),
    ("change", "Đổi mật khẩu"),
    ("save_status", "Lưu trạng thái"),
    ("speaker", "Loa"),
    ("speaker_off", "Tắt loa"),
    ("scan_qr", "Quét QR"),
    ("qr_picture", "Ảnh QR"),
    ("must_save", "Hãy lưu bản sao trước khi tiếp tục."),
    ("enter_password", "Nhập mật khẩu của bản sao này trước."),
    ("choose_file", "Chọn tệp bản sao kho khóa."),
    ("added", "Đã thêm liên hệ"),
    ("saved_prefix", "Đã lưu"),
];

const TH: &[(&str, &str)] = &[
    ("remove", "ลบ"),
    ("share", "แชร์คำเชิญ"),
    ("paste", "วางคำเชิญ"),
    ("paste_body", "วางลิงก์ ghalbol:// หรือ https://ghalbol.com/connect/."),
    ("add", "เพิ่มด้วยกุญแจสาธารณะ"),
    ("add_body", "แขกเก็บกุญแจสาธารณะของเจ้าบ้าน เจ้าบ้านไม่ต้องมีกุญแจของคุณก่อน"),
    ("contacts", "รายชื่อ"),
    ("none", "ยังไม่มีรายชื่อ"),
    ("blocked", "ที่บล็อก"),
    ("blocked_empty", "ไม่มีคนที่บล็อก วางกุญแจสาธารณะเพื่อบล็อกคนที่อยู่ในรายชื่อ"),
    ("delivery", "ที่เก็บการส่ง"),
    ("log", "บันทึกแอป"),
    ("key", "กุญแจส่วนตัว"),
    ("key_body", "ใส่รหัสแอปแล้วค่อยแสดงกุญแจ ทำเฉพาะที่ส่วนตัว"),
    ("backup", "ส่งออกสำเนา"),
    ("backup_body", "บันทึกคลังกุญแจที่เข้ารหัส เปิดบนเครื่องอื่นยังต้องใช้รหัสแอป"),
    ("password", "เปลี่ยนรหัส"),
    ("password_body", "รหัสปัจจุบันในช่องคำเชิญ รหัสใหม่ในช่องชื่อ สำเนาเก่ายังใช้รหัสเก่า"),
    ("about", "เกี่ยวกับ Ghal Bol"),
    ("about_body", "ข้อความเข้ารหัสต้นทางถึงปลายทาง แต่ละเครื่องเก็บบทสนทนาของตัวเอง"),
    ("no_status", "ยังไม่ตั้งสถานะ"),
    ("save_backup", "บันทึกสำเนา"),
    ("save_backup_body", "บันทึกสำเนาที่เข้ารหัสก่อนแชท ตัวตนนี้กู้ไม่ได้ถ้าไม่มีสำเนาและรหัส"),
    ("back", "กลับ"),
    ("join_go", "เข้าร่วม"),
    ("add_go", "เพิ่มรายชื่อ"),
    ("add_short", "เพิ่ม"),
    ("toggle", "สลับการบล็อก"),
    ("refresh", "รีเฟรช"),
    ("show_key", "แสดงกุญแจ"),
    ("save", "บันทึกสำเนา"),
    ("change", "เปลี่ยนรหัส"),
    ("save_status", "บันทึกสถานะ"),
    ("speaker", "ลำโพง"),
    ("speaker_off", "ปิดลำโพง"),
    ("scan_qr", "สแกนคิวอาร์"),
    ("qr_picture", "รูปคิวอาร์"),
    ("must_save", "บันทึกสำเนาก่อนไปต่อ"),
    ("enter_password", "ใส่รหัสของสำเนานี้ก่อน"),
    ("choose_file", "เลือกไฟล์สำเนาคลังกุญแจ"),
    ("added", "เพิ่มรายชื่อแล้ว"),
    ("saved_prefix", "บันทึกแล้ว"),
];

const ID: &[(&str, &str)] = &[
    ("remove", "Hapus"),
    ("share", "Bagikan undangan"),
    ("paste", "Tempel undangan"),
    ("paste_body", "Tempel tautan ghalbol:// atau https://ghalbol.com/connect/."),
    ("add", "Tambah dengan kunci publik"),
    ("add_body", "Tamu menyimpan kunci publik tuan rumah. Tuan rumah tidak perlu kunci Anda lebih dulu."),
    ("contacts", "Kontak"),
    ("none", "Belum ada kontak"),
    ("blocked", "Diblokir"),
    ("blocked_empty", "Tidak ada kontak diblokir. Tempel kunci publik untuk memblokir orang yang sudah ada di daftar."),
    ("delivery", "Penyimpanan pengiriman"),
    ("log", "Catatan aplikasi"),
    ("key", "Kunci pribadi"),
    ("key_body", "Ketik kata sandi aplikasi lalu tampilkan kunci. Lakukan hanya di tempat pribadi."),
    ("backup", "Ekspor cadangan"),
    ("backup_body", "Menyimpan brankas kunci terenkripsi. Kata sandi tetap diperlukan di perangkat lain."),
    ("password", "Ubah kata sandi"),
    ("password_body", "Kata sandi sekarang di kolom undangan. Yang baru di kolom nama. Cadangan lama tetap memakai kata sandi lama."),
    ("about", "Tentang Ghal Bol"),
    ("about_body", "Pesan terenkripsi ujung ke ujung. Setiap perangkat menyimpan percakapannya sendiri."),
    ("no_status", "Belum ada status"),
    ("save_backup", "Simpan cadangan"),
    ("save_backup_body", "Simpan cadangan terenkripsi sebelum mengobrol. Identitas ini tidak bisa dipulihkan tanpa cadangan dan kata sandi."),
    ("back", "Kembali"),
    ("join_go", "Gabung"),
    ("add_go", "Tambah kontak"),
    ("add_short", "Tambah"),
    ("toggle", "Ubah blokir"),
    ("refresh", "Segarkan"),
    ("show_key", "Tampilkan kunci"),
    ("save", "Simpan cadangan"),
    ("change", "Ubah kata sandi"),
    ("save_status", "Simpan status"),
    ("speaker", "Pengeras suara"),
    ("speaker_off", "Pengeras suara mati"),
    ("scan_qr", "Pindai QR"),
    ("qr_picture", "Gambar QR"),
    ("must_save", "Simpan cadangan sebelum melanjutkan."),
    ("enter_password", "Masukkan dulu kata sandi cadangan ini."),
    ("choose_file", "Pilih berkas cadangan brankas kunci."),
    ("added", "Kontak ditambahkan"),
    ("saved_prefix", "Tersimpan"),
];

const SW: &[(&str, &str)] = &[
    ("remove", "Ondoa"),
    ("share", "Shiriki mwaliko"),
    ("paste", "Bandika mwaliko"),
    ("paste_body", "Bandika kiungo cha ghalbol:// au https://ghalbol.com/connect/."),
    ("add", "Ongeza kwa ufunguo wa umma"),
    ("add_body", "Mgeni huhifadhi ufunguo wa umma wa mwenyeji. Mwenyeji hahitaji wako kwanza."),
    ("contacts", "Anwani"),
    ("none", "Bado hakuna anwani"),
    ("blocked", "Waliozuiliwa"),
    ("blocked_empty", "Hakuna aliyezuiliwa. Bandika ufunguo wa umma ili kumzuia aliye kwenye orodha."),
    ("delivery", "Hifadhi ya upelekaji"),
    ("log", "Kumbukumbu ya programu"),
    ("key", "Ufunguo wa faragha"),
    ("key_body", "Andika nenosiri la programu kisha uonyeshe ufunguo. Fanya hivi mahali pa faragha pekee."),
    ("backup", "Hamisha nakala"),
    ("backup_body", "Huhifadhi hazina ya funguo iliyosimbwa. Bado unahitaji nenosiri kuifungua kwenye kifaa kingine."),
    ("password", "Badilisha nenosiri"),
    ("password_body", "Nenosiri la sasa kwenye sehemu ya mwaliko. Jipya kwenye sehemu ya jina. Nakala za zamani hubaki na nenosiri la zamani."),
    ("about", "Kuhusu Ghal Bol"),
    ("about_body", "Ujumbe uliosimbwa kuanzia mwisho hadi mwisho. Kila kifaa huhifadhi mazungumzo yake."),
    ("no_status", "Hakuna hali"),
    ("save_backup", "Hifadhi nakala"),
    ("save_backup_body", "Hifadhi nakala iliyosimbwa kabla ya kuzungumza. Utambulisho huu haurudi bila nakala na nenosiri."),
    ("back", "Rudi"),
    ("join_go", "Jiunge"),
    ("add_go", "Ongeza anwani"),
    ("add_short", "Ongeza"),
    ("toggle", "Badilisha kizuizi"),
    ("refresh", "Onyesha upya"),
    ("show_key", "Onyesha ufunguo"),
    ("save", "Hifadhi nakala"),
    ("change", "Badilisha nenosiri"),
    ("save_status", "Hifadhi hali"),
    ("speaker", "Spika"),
    ("speaker_off", "Spika imezimwa"),
    ("scan_qr", "Changanua QR"),
    ("qr_picture", "Picha ya QR"),
    ("must_save", "Hifadhi nakala kabla ya kuendelea."),
    ("enter_password", "Andika kwanza nenosiri la nakala hii."),
    ("choose_file", "Chagua faili ya nakala ya hazina ya funguo."),
    ("added", "Anwani imeongezwa"),
    ("saved_prefix", "Imehifadhiwa"),
];

const BN: &[(&str, &str)] = &[
    ("remove", "সরান"),
    ("share", "আমন্ত্রণ ভাগ করুন"),
    ("paste", "আমন্ত্রণ আটকান"),
    ("paste_body", "একটি ghalbol:// বা https://ghalbol.com/connect/ লিঙ্ক আটকান।"),
    ("add", "সর্বজনীন চাবি দিয়ে যোগ"),
    ("add_body", "অতিথি আয়োজকের সর্বজনীন চাবি রাখে। আয়োজকের আগে আপনার চাবি লাগে না।"),
    ("contacts", "যোগাযোগ"),
    ("none", "এখনও কোনো যোগাযোগ নেই"),
    ("blocked", "অবরুদ্ধ"),
    ("blocked_empty", "কেউ অবরুদ্ধ নয়। তালিকার কাউকে আটকাতে সর্বজনীন চাবি আটকান।"),
    ("delivery", "বিতরণের ভাণ্ডার"),
    ("log", "অ্যাপের খাতা"),
    ("key", "ব্যক্তিগত চাবি"),
    ("key_body", "অ্যাপের পাসওয়ার্ড লিখে তারপর চাবি দেখান। শুধু নির্জনে করুন।"),
    ("backup", "সংরক্ষণ রপ্তানি"),
    ("backup_body", "সঙ্কেতায়িত চাবিভাণ্ডার সেভ করে। অন্য যন্ত্রে খুলতে পাসওয়ার্ড লাগে।"),
    ("password", "পাসওয়ার্ড বদল"),
    ("password_body", "বর্তমান পাসওয়ার্ড আমন্ত্রণের ঘরে। নতুনটি নামের ঘরে। পুরনো সংরক্ষণ পুরনো পাসওয়ার্ড রাখে।"),
    ("about", "ঘাল বোল সম্পর্কে"),
    ("about_body", "প্রান্ত থেকে প্রান্ত সঙ্কেতায়িত বার্তা। প্রতিটি যন্ত্র নিজের কথা রাখে।"),
    ("no_status", "কোনো অবস্থা নেই"),
    ("save_backup", "সংরক্ষণ রাখুন"),
    ("save_backup_body", "কথা বলার আগে সঙ্কেতায়িত সংরক্ষণ রাখুন। এটি ও পাসওয়ার্ড না থাকলে এই পরিচয় ফেরে না।"),
    ("back", "পিছনে"),
    ("join_go", "যোগ দিন"),
    ("add_go", "যোগাযোগ যোগ"),
    ("add_short", "যোগ"),
    ("toggle", "অবরোধ বদল"),
    ("refresh", "সতেজ"),
    ("show_key", "চাবি দেখান"),
    ("save", "সংরক্ষণ রাখুন"),
    ("change", "পাসওয়ার্ড বদল"),
    ("save_status", "অবস্থা রাখুন"),
    ("speaker", "স্পিকার"),
    ("speaker_off", "স্পিকার বন্ধ"),
    ("scan_qr", "কিউআর পড়ুন"),
    ("qr_picture", "কিউআর ছবি"),
    ("must_save", "এগোতে হলে আগে সংরক্ষণ রাখুন।"),
    ("enter_password", "আগে এই সংরক্ষণের পাসওয়ার্ড লিখুন।"),
    ("choose_file", "চাবিভাণ্ডারের সংরক্ষণ ফাইল বেছে নিন।"),
    ("added", "যোগাযোগ যোগ হয়েছে"),
    ("saved_prefix", "রাখা হয়েছে"),
];

const AS: &[(&str, &str)] = &[
    ("remove", "আঁতৰাওক"),
    ("share", "নিমন্ত্ৰণ ভাগ কৰক"),
    ("paste", "নিমন্ত্ৰণ আঠাওক"),
    ("paste_body", "ghalbol:// বা https://ghalbol.com/connect/ লিংক আঠাওক।"),
    ("add", "ৰাজহুৱা চাবিৰে যোগ"),
    ("add_body", "অতিথিয়ে গৃহস্থৰ ৰাজহুৱা চাবি ৰাখে। গৃহস্থক আগেয়ে আপোনাৰ চাবি নালাগে।"),
    ("contacts", "যোগাযোগ"),
    ("none", "এতিয়াও যোগাযোগ নাই"),
    ("blocked", "অৱৰুদ্ধ"),
    ("blocked_empty", "কোনেও অৱৰুদ্ধ নহয়। তালিকাৰ মানুহক ৰ’বলৈ ৰাজহুৱা চাবি আঠাওক।"),
    ("delivery", "বিতৰণৰ ভঁৰাল"),
    ("log", "এপৰ খতিয়ান"),
    ("key", "ব্যক্তিগত চাবি"),
    ("key_body", "এপৰ পাছৱৰ্ড লিখি তাৰ পাছত চাবি দেখুৱাওক। কেৱল নিৰ্জনে কৰক।"),
    ("backup", "সংৰক্ষণ ৰপ্তানি"),
    ("backup_body", "সংকেতায়িত চাবিভঁৰাল সাঁচে। আন যন্ত্ৰত খুলিবলৈ পাছৱৰ্ড লাগে।"),
    ("password", "পাছৱৰ্ড সলনি"),
    ("password_body", "বৰ্তমান পাছৱৰ্ড নিমন্ত্ৰণৰ ঘৰত। নতুনটো নামৰ ঘৰত। পুৰণি সংৰক্ষণে পুৰণি পাছৱৰ্ড ৰাখে।"),
    ("about", "ঘাল বোলৰ বিষয়ে"),
    ("about_body", "মূৰৰ পৰা মূৰলৈ সংকেতায়িত বাৰ্তা। প্ৰতিটো যন্ত্ৰই নিজৰ কথা ৰাখে।"),
    ("no_status", "কোনো অৱস্থা নাই"),
    ("save_backup", "সংৰক্ষণ ৰাখক"),
    ("save_backup_body", "কথা পাতিবৰ আগতে সংকেতায়িত সংৰক্ষণ ৰাখক। ই আৰু পাছৱৰ্ড নহ’লে এই পৰিচয় উভতি নাহে।"),
    ("back", "পিছলৈ"),
    ("join_go", "যোগ দিয়ক"),
    ("add_go", "যোগাযোগ যোগ"),
    ("add_short", "যোগ"),
    ("toggle", "অৱৰোধ সলনি"),
    ("refresh", "সতেজ"),
    ("show_key", "চাবি দেখুৱাওক"),
    ("save", "সংৰক্ষণ ৰাখক"),
    ("change", "পাছৱৰ্ড সলনি"),
    ("save_status", "অৱস্থা ৰাখক"),
    ("speaker", "স্পীকাৰ"),
    ("speaker_off", "স্পীকাৰ বন্ধ"),
    ("scan_qr", "কিউআৰ পঢ়ক"),
    ("qr_picture", "কিউআৰ ছবি"),
    ("must_save", "আগবাঢ়িবলৈ আগেয়ে সংৰক্ষণ ৰাখক।"),
    ("enter_password", "আগেয়ে এই সংৰক্ষণৰ পাছৱৰ্ড লিখক।"),
    ("choose_file", "চাবিভঁৰালৰ সংৰক্ষণ ফাইল বাছক।"),
    ("added", "যোগাযোগ যোগ হ’ল"),
    ("saved_prefix", "ৰখা হ’ল"),
];

const GU: &[(&str, &str)] = &[
    ("remove", "દૂર કરો"),
    ("share", "આમંત્રણ વહેંચો"),
    ("paste", "આમંત્રણ ચોંટાડો"),
    ("paste_body", "ghalbol:// અથવા https://ghalbol.com/connect/ કડી ચોંટાડો."),
    ("add", "જાહેર ચાવી વડે ઉમેરો"),
    ("add_body", "મહેમાન યજમાનની જાહેર ચાવી રાખે છે. યજમાનને પહેલાં તમારી ચાવી જોઈતી નથી."),
    ("contacts", "સંપર્ક"),
    ("none", "હજી સંપર્ક નથી"),
    ("blocked", "અવરોધિત"),
    ("blocked_empty", "કોઈ અવરોધિત નથી. યાદીના કોઈને અટકાવવા જાહેર ચાવી ચોંટાડો."),
    ("delivery", "વિતરણનો ભંડાર"),
    ("log", "એપનો હિસાબ"),
    ("key", "ખાનગી ચાવી"),
    ("key_body", "એપનો પાસવર્ડ લખી પછી ચાવી બતાવો. ફક્ત એકાંતમાં કરો."),
    ("backup", "નકલ નિકાસ"),
    ("backup_body", "સાંકેતિક ચાવીભંડાર સાચવે છે. બીજા સાધન પર ખોલવા પાસવર્ડ જોઈએ."),
    ("password", "પાસવર્ડ બદલો"),
    ("password_body", "હાલનો પાસવર્ડ આમંત્રણના ખાનામાં. નવો નામના ખાનામાં. જૂની નકલ જૂનો પાસવર્ડ રાખે છે."),
    ("about", "ઘાલ બોલ વિશે"),
    ("about_body", "છેડાથી છેડા સાંકેતિક સંદેશ. દરેક સાધન પોતાની વાત રાખે છે."),
    ("no_status", "કોઈ સ્થિતિ નથી"),
    ("save_backup", "નકલ સાચવો"),
    ("save_backup_body", "વાત પહેલાં સાંકેતિક નકલ સાચવો. આ અને પાસવર્ડ વગર આ ઓળખ પાછી નથી આવતી."),
    ("back", "પાછળ"),
    ("join_go", "જોડાઓ"),
    ("add_go", "સંપર્ક ઉમેરો"),
    ("add_short", "ઉમેરો"),
    ("toggle", "અવરોધ બદલો"),
    ("refresh", "તાજું"),
    ("show_key", "ચાવી બતાવો"),
    ("save", "નકલ સાચવો"),
    ("change", "પાસવર્ડ બદલો"),
    ("save_status", "સ્થિતિ સાચવો"),
    ("speaker", "સ્પીકર"),
    ("speaker_off", "સ્પીકર બંધ"),
    ("scan_qr", "ક્યુઆર વાંચો"),
    ("qr_picture", "ક્યુઆર ચિત્ર"),
    ("must_save", "આગળ વધતાં પહેલાં નકલ સાચવો."),
    ("enter_password", "પહેલાં આ નકલનો પાસવર્ડ લખો."),
    ("choose_file", "ચાવીભંડારની નકલ ફાઈલ પસંદ કરો."),
    ("added", "સંપર્ક ઉમેરાયો"),
    ("saved_prefix", "સાચવ્યું"),
];

const KN: &[(&str, &str)] = &[
    ("remove", "ತೆಗೆದುಹಾಕಿ"),
    ("share", "ಆಮಂತ್ರಣ ಹಂಚಿ"),
    ("paste", "ಆಮಂತ್ರಣ ಅಂಟಿಸಿ"),
    ("paste_body", "ghalbol:// ಅಥವಾ https://ghalbol.com/connect/ ಕೊಂಡಿ ಅಂಟಿಸಿ."),
    ("add", "ಸಾರ್ವಜನಿಕ ಕೀಲಿಯಿಂದ ಸೇರಿಸಿ"),
    ("add_body", "ಅತಿಥಿ ಆತಿಥೇಯರ ಸಾರ್ವಜನಿಕ ಕೀಲಿ ಇಡುತ್ತಾನೆ. ಆತಿಥೇಯರಿಗೆ ಮೊದಲು ನಿಮ್ಮ ಕೀಲಿ ಬೇಡ."),
    ("contacts", "ಸಂಪರ್ಕಗಳು"),
    ("none", "ಇನ್ನೂ ಸಂಪರ್ಕಗಳಿಲ್ಲ"),
    ("blocked", "ತಡೆದವು"),
    ("blocked_empty", "ಯಾರನ್ನೂ ತಡೆದಿಲ್ಲ. ಪಟ್ಟಿಯವರನ್ನು ತಡೆಯಲು ಸಾರ್ವಜನಿಕ ಕೀಲಿ ಅಂಟಿಸಿ."),
    ("delivery", "ತಲುಪಿಸುವಿಕೆಯ ಉಗ್ರಾಣ"),
    ("log", "ಅಪ್ಲಿಕೇಶನ್ ದಾಖಲೆ"),
    ("key", "ಖಾಸಗಿ ಕೀಲಿ"),
    ("key_body", "ಅಪ್ಲಿಕೇಶನ್ ಗುಪ್ತಪದ ಬರೆದು ನಂತರ ಕೀಲಿ ತೋರಿಸಿ. ಏಕಾಂತದಲ್ಲಿ ಮಾತ್ರ."),
    ("backup", "ನಕಲು ರಫ್ತು"),
    ("backup_body", "ಗೂಢಲಿಪಿಯ ಕೀಲಿಗೂಡು ಉಳಿಸುತ್ತದೆ. ಬೇರೆ ಸಾಧನದಲ್ಲಿ ತೆರೆಯಲು ಗುಪ್ತಪದ ಬೇಕು."),
    ("password", "ಗುಪ್ತಪದ ಬದಲಿಸಿ"),
    ("password_body", "ಈಗಿನ ಗುಪ್ತಪದ ಆಮಂತ್ರಣದ ಅಂಕಣದಲ್ಲಿ. ಹೊಸದು ಹೆಸರಿನ ಅಂಕಣದಲ್ಲಿ. ಹಳೆ ನಕಲು ಹಳೆ ಗುಪ್ತಪದವನ್ನೇ ಇಡುತ್ತದೆ."),
    ("about", "ಘಾಲ್ ಬೋಲ್ ಬಗ್ಗೆ"),
    ("about_body", "ತುದಿಯಿಂದ ತುದಿಗೆ ಗೂಢಲಿಪಿ ಸಂದೇಶ. ಪ್ರತಿ ಸಾಧನ ತನ್ನ ಮಾತನ್ನೇ ಇಡುತ್ತದೆ."),
    ("no_status", "ಸ್ಥಿತಿ ಇಲ್ಲ"),
    ("save_backup", "ನಕಲು ಉಳಿಸಿ"),
    ("save_backup_body", "ಮಾತಾಡುವ ಮೊದಲು ಗೂಢ ನಕಲು ಉಳಿಸಿ. ಇದು ಮತ್ತು ಗುಪ್ತಪದ ಇಲ್ಲದೆ ಈ ಗುರುತು ಹಿಂದಿರುಗುವುದಿಲ್ಲ."),
    ("back", "ಹಿಂದೆ"),
    ("join_go", "ಸೇರಿ"),
    ("add_go", "ಸಂಪರ್ಕ ಸೇರಿಸಿ"),
    ("add_short", "ಸೇರಿಸಿ"),
    ("toggle", "ತಡೆ ಬದಲಿಸಿ"),
    ("refresh", "ನವೀಕರಿಸಿ"),
    ("show_key", "ಕೀಲಿ ತೋರಿಸಿ"),
    ("save", "ನಕಲು ಉಳಿಸಿ"),
    ("change", "ಗುಪ್ತಪದ ಬದಲಿಸಿ"),
    ("save_status", "ಸ್ಥಿತಿ ಉಳಿಸಿ"),
    ("speaker", "ಧ್ವನಿವರ್ಧಕ"),
    ("speaker_off", "ಧ್ವನಿವರ್ಧಕ ಆರಿಸಿ"),
    ("scan_qr", "ಕ್ಯುಆರ್ ಓದಿ"),
    ("qr_picture", "ಕ್ಯುಆರ್ ಚಿತ್ರ"),
    ("must_save", "ಮುಂದುವರಿಯುವ ಮೊದಲು ನಕಲು ಉಳಿಸಿ."),
    ("enter_password", "ಮೊದಲು ಈ ನಕಲಿನ ಗುಪ್ತಪದ ಬರೆಯಿರಿ."),
    ("choose_file", "ಕೀಲಿಗೂಡಿನ ನಕಲು ಕಡತ ಆಯ್ಕೆಮಾಡಿ."),
    ("added", "ಸಂಪರ್ಕ ಸೇರಿಸಲಾಗಿದೆ"),
    ("saved_prefix", "ಉಳಿಸಲಾಗಿದೆ"),
];

const ML: &[(&str, &str)] = &[
    ("remove", "നീക്കം ചെയ്യുക"),
    ("share", "ക്ഷണം പങ്കിടുക"),
    ("paste", "ക്ഷണം ഒട്ടിക്കുക"),
    ("paste_body", "ghalbol:// അല്ലെങ്കിൽ https://ghalbol.com/connect/ കണ്ണി ഒട്ടിക്കുക."),
    ("add", "പൊതു ചാവി കൊണ്ട് ചേർക്കുക"),
    ("add_body", "അതിഥി ആതിഥേയന്റെ പൊതു ചാവി സൂക്ഷിക്കുന്നു. ആതിഥേയന് ആദ്യം നിങ്ങളുടെ ചാവി വേണ്ട."),
    ("contacts", "ബന്ധങ്ങൾ"),
    ("none", "ഇനിയും ബന്ധങ്ങളില്ല"),
    ("blocked", "തടഞ്ഞവ"),
    ("blocked_empty", "ആരെയും തടഞ്ഞിട്ടില്ല. പട്ടികയിലുള്ളവരെ തടയാൻ പൊതു ചാവി ഒട്ടിക്കുക."),
    ("delivery", "എത്തിക്കലിന്റെ ശേഖരം"),
    ("log", "ആപ്പ് രേഖ"),
    ("key", "സ്വകാര്യ ചാവി"),
    ("key_body", "ആപ്പ് പാസ്‌വേഡ് എഴുതി പിന്നെ ചാവി കാണിക്കുക. ഒറ്റയ്ക്കുള്ളിടത്ത് മാത്രം."),
    ("backup", "പകർപ്പ് കയറ്റുമതി"),
    ("backup_body", "രഹസ്യമാക്കിയ ചാവിപ്പെട്ടി സൂക്ഷിക്കുന്നു. മറ്റൊരു ഉപകരണത്തിൽ തുറക്കാൻ പാസ്‌വേഡ് വേണം."),
    ("password", "പാസ്‌വേഡ് മാറ്റുക"),
    ("password_body", "ഇപ്പോഴത്തെ പാസ്‌വേഡ് ക്ഷണത്തിന്റെ കളത്തിൽ. പുതിയത് പേരിന്റെ കളത്തിൽ. പഴയ പകർപ്പ് പഴയ പാസ്‌വേഡ് വയ്ക്കുന്നു."),
    ("about", "ഘാൽ ബോൾ സംബന്ധിച്ച്"),
    ("about_body", "അറ്റം മുതൽ അറ്റം വരെ രഹസ്യ സന്ദേശം. ഓരോ ഉപകരണവും സ്വന്തം സംഭാഷണം സൂക്ഷിക്കുന്നു."),
    ("no_status", "അവസ്ഥയില്ല"),
    ("save_backup", "പകർപ്പ് സൂക്ഷിക്കുക"),
    ("save_backup_body", "സംസാരിക്കുന്നതിന് മുമ്പ് രഹസ്യ പകർപ്പ് സൂക്ഷിക്കുക. ഇതും പാസ്‌വേഡും ഇല്ലെങ്കിൽ ഈ തിരിച്ചറിയൽ തിരിച്ചുവരില്ല."),
    ("back", "പിന്നോട്ട്"),
    ("join_go", "ചേരുക"),
    ("add_go", "ബന്ധം ചേർക്കുക"),
    ("add_short", "ചേർക്കുക"),
    ("toggle", "തടയൽ മാറ്റുക"),
    ("refresh", "പുതുക്കുക"),
    ("show_key", "ചാവി കാണിക്കുക"),
    ("save", "പകർപ്പ് സൂക്ഷിക്കുക"),
    ("change", "പാസ്‌വേഡ് മാറ്റുക"),
    ("save_status", "അവസ്ഥ സൂക്ഷിക്കുക"),
    ("speaker", "ശബ്ദപെട്ടി"),
    ("speaker_off", "ശബ്ദപെട്ടി അണച്ചു"),
    ("scan_qr", "ക്യൂആർ വായിക്കുക"),
    ("qr_picture", "ക്യൂആർ ചിത്രം"),
    ("must_save", "തുടരുന്നതിന് മുമ്പ് പകർപ്പ് സൂക്ഷിക്കുക."),
    ("enter_password", "ആദ്യം ഈ പകർപ്പിന്റെ പാസ്‌വേഡ് എഴുതുക."),
    ("choose_file", "ചാവിപ്പെട്ടിയുടെ പകർപ്പ് ഫയൽ തിരഞ്ഞെടുക്കുക."),
    ("added", "ബന്ധം ചേർത്തു"),
    ("saved_prefix", "സൂക്ഷിച്ചു"),
];

const MR: &[(&str, &str)] = &[
    ("remove", "काढा"),
    ("share", "आमंत्रण वाटा"),
    ("paste", "आमंत्रण चिकटवा"),
    ("paste_body", "ghalbol:// किंवा https://ghalbol.com/connect/ दुवा चिकटवा."),
    ("add", "सार्वजनिक किल्लीने जोडा"),
    ("add_body", "पाहुणा यजमानाची सार्वजनिक किल्ली ठेवतो. यजमानाला आधी तुमची किल्ली नको."),
    ("contacts", "संपर्क"),
    ("none", "अजून संपर्क नाहीत"),
    ("blocked", "अडवलेले"),
    ("blocked_empty", "कोणी अडवलेले नाही. यादीतील माणसाला अडवण्यासाठी सार्वजनिक किल्ली चिकटवा."),
    ("delivery", "पोहोचवणीचे कोठार"),
    ("log", "अॅप नोंद"),
    ("key", "खाजगी किल्ली"),
    ("key_body", "अॅप पासवर्ड लिहून मग किल्ली दाखवा. फक्त एकांतात करा."),
    ("backup", "प्रत निर्यात"),
    ("backup_body", "सांकेतिक किल्लीकोठार जतन करते. दुसऱ्या साधनावर उघडायला पासवर्ड लागतो."),
    ("password", "पासवर्ड बदला"),
    ("password_body", "सध्याचा पासवर्ड आमंत्रणाच्या खोळीत. नवा नावाच्या खोळीत. जुनी प्रत जुना पासवर्ड ठेवते."),
    ("about", "घाळ बोल बद्दल"),
    ("about_body", "टोकापासून टोकापर्यंत सांकेतिक संदेश. प्रत्येक साधन आपली गोष्ट ठेवते."),
    ("no_status", "स्थिती नाही"),
    ("save_backup", "प्रत जतन करा"),
    ("save_backup_body", "बोलण्यापूर्वी सांकेतिक प्रत जतन करा. ही आणि पासवर्ड नसेल तर ही ओळख परत येत नाही."),
    ("back", "मागे"),
    ("join_go", "सामील व्हा"),
    ("add_go", "संपर्क जोडा"),
    ("add_short", "जोडा"),
    ("toggle", "अडथळा बदला"),
    ("refresh", "ताजे करा"),
    ("show_key", "किल्ली दाखवा"),
    ("save", "प्रत जतन करा"),
    ("change", "पासवर्ड बदला"),
    ("save_status", "स्थिती जतन करा"),
    ("speaker", "ध्वनिवर्धक"),
    ("speaker_off", "ध्वनिवर्धक बंद"),
    ("scan_qr", "क्यूआर वाचा"),
    ("qr_picture", "क्यूआर चित्र"),
    ("must_save", "पुढे जाण्यापूर्वी प्रत जतन करा."),
    ("enter_password", "आधी या प्रतीचा पासवर्ड लिहा."),
    ("choose_file", "किल्लीकोठाराची प्रत फाइल निवडा."),
    ("added", "संपर्क जोडला"),
    ("saved_prefix", "जतन केले"),
];

const TA: &[(&str, &str)] = &[
    ("remove", "நீக்கு"),
    ("share", "அழைப்பைப் பகிர்"),
    ("paste", "அழைப்பை ஒட்டு"),
    ("paste_body", "ghalbol:// அல்லது https://ghalbol.com/connect/ இணைப்பை ஒட்டுங்கள்."),
    ("add", "பொதுத் திறவுகோலால் சேர்"),
    ("add_body", "விருந்தினர் விருந்தோம்புநரின் பொதுத் திறவுகோலை வைக்கிறார். விருந்தோம்புநருக்கு முதலில் உங்கள் திறவுகோல் வேண்டாம்."),
    ("contacts", "தொடர்புகள்"),
    ("none", "இன்னும் தொடர்புகள் இல்லை"),
    ("blocked", "தடுக்கப்பட்டவை"),
    ("blocked_empty", "யாரும் தடுக்கப்படவில்லை. பட்டியலிலுள்ளவரைத் தடுக்க பொதுத் திறவுகோலை ஒட்டுங்கள்."),
    ("delivery", "சேர்ப்பின் கிடங்கு"),
    ("log", "செயலி பதிவு"),
    ("key", "தனித் திறவுகோல்"),
    ("key_body", "செயலி கடவுச்சொல்லை எழுதிப் பின் திறவுகோலைக் காட்டுங்கள். தனிமையில் மட்டும்."),
    ("backup", "நகலை ஏற்றுமதி"),
    ("backup_body", "மறைகுறியாக்கப்பட்ட திறவுகோல் பெட்டகத்தைச் சேமிக்கிறது. வேறு கருவியில் திறக்க கடவுச்சொல் வேண்டும்."),
    ("password", "கடவுச்சொல்லை மாற்று"),
    ("password_body", "தற்போதைய கடவுச்சொல் அழைப்புப் பெட்டியில். புதியது பெயர்ப் பெட்டியில். பழைய நகல் பழைய கடவுச்சொல்லை வைக்கும்."),
    ("about", "கால் போல் பற்றி"),
    ("about_body", "முனை முதல் முனை வரை மறைகுறியாக்கப்பட்ட செய்தி. ஒவ்வொரு கருவியும் தன் உரையாடலை வைக்கும்."),
    ("no_status", "நிலை இல்லை"),
    ("save_backup", "நகலைச் சேமி"),
    ("save_backup_body", "பேசுவதற்கு முன் மறைகுறியாக்கப்பட்ட நகலைச் சேமியுங்கள். இதுவும் கடவுச்சொல்லும் இல்லாவிட்டால் இந்த அடையாளம் திரும்பாது."),
    ("back", "பின்"),
    ("join_go", "சேர்"),
    ("add_go", "தொடர்பைச் சேர்"),
    ("add_short", "சேர்"),
    ("toggle", "தடுப்பை மாற்று"),
    ("refresh", "புதுப்பி"),
    ("show_key", "திறவுகோலைக் காட்டு"),
    ("save", "நகலைச் சேமி"),
    ("change", "கடவுச்சொல்லை மாற்று"),
    ("save_status", "நிலையைச் சேமி"),
    ("speaker", "ஒலிபெருக்கி"),
    ("speaker_off", "ஒலிபெருக்கி அணைந்தது"),
    ("scan_qr", "கியூஆர் படி"),
    ("qr_picture", "கியூஆர் படம்"),
    ("must_save", "தொடரும் முன் நகலைச் சேமியுங்கள்."),
    ("enter_password", "முதலில் இந்த நகலின் கடவுச்சொல்லை எழுதுங்கள்."),
    ("choose_file", "திறவுகோல் பெட்டக நகல் கோப்பைத் தேர்ந்தெடுங்கள்."),
    ("added", "தொடர்பு சேர்க்கப்பட்டது"),
    ("saved_prefix", "சேமிக்கப்பட்டது"),
];

const TE: &[(&str, &str)] = &[
    ("remove", "తీసివేయి"),
    ("share", "ఆహ్వానం పంచు"),
    ("paste", "ఆహ్వానం అతికించు"),
    ("paste_body", "ghalbol:// లేదా https://ghalbol.com/connect/ లింకు అతికించండి."),
    ("add", "బహిరంగ తాళంతో చేర్చు"),
    ("add_body", "అతిథి ఆతిథ్యదాత బహిరంగ తాళం ఉంచుతాడు. ఆతిథ్యదాతకు ముందు మీ తాళం అవసరం లేదు."),
    ("contacts", "పరిచయాలు"),
    ("none", "ఇంకా పరిచయాలు లేవు"),
    ("blocked", "నిరోధించినవి"),
    ("blocked_empty", "ఎవరినీ నిరోధించలేదు. జాబితాలోని వారిని ఆపేందుకు బహిరంగ తాళం అతికించండి."),
    ("delivery", "చేరవేత నిల్వ"),
    ("log", "యాప్ చిట్టా"),
    ("key", "రహస్య తాళం"),
    ("key_body", "యాప్ సాంకేతిక పదం రాసి తర్వాత తాళం చూపండి. ఏకాంతంలో మాత్రమే."),
    ("backup", "నకలు ఎగుమతి"),
    ("backup_body", "గుప్తీకరించిన తాళపు పెట్టెను దాచుతుంది. మరో పరికరంలో తెరవడానికి సాంకేతిక పదం కావాలి."),
    ("password", "సాంకేతిక పదం మార్చు"),
    ("password_body", "ప్రస్తుత సాంకేతిక పదం ఆహ్వానపు గదిలో. కొత్తది పేరు గదిలో. పాత నకలు పాత పదమే ఉంచుతుంది."),
    ("about", "ఘాల్ బోల్ గురించి"),
    ("about_body", "చివరి నుంచి చివరి వరకు గుప్త సందేశం. ప్రతి పరికరం తన సంభాషణనే ఉంచుతుంది."),
    ("no_status", "స్థితి లేదు"),
    ("save_backup", "నకలు దాచండి"),
    ("save_backup_body", "మాట్లాడే ముందు గుప్త నకలు దాచండి. ఇది మరియు సాంకేతిక పదం లేకుంటే ఈ గుర్తింపు తిరిగి రాదు."),
    ("back", "వెనక్కి"),
    ("join_go", "చేరండి"),
    ("add_go", "పరిచయం చేర్చు"),
    ("add_short", "చేర్చు"),
    ("toggle", "నిరోధం మార్చు"),
    ("refresh", "తాజా చేయి"),
    ("show_key", "తాళం చూపు"),
    ("save", "నకలు దాచు"),
    ("change", "సాంకేతిక పదం మార్చు"),
    ("save_status", "స్థితి దాచు"),
    ("speaker", "ధ్వనివర్ధకం"),
    ("speaker_off", "ధ్వనివర్ధకం ఆపు"),
    ("scan_qr", "క్యూఆర్ చదువు"),
    ("qr_picture", "క్యూఆర్ బొమ్మ"),
    ("must_save", "కొనసాగే ముందు నకలు దాచండి."),
    ("enter_password", "ముందు ఈ నకలు సాంకేతిక పదం రాయండి."),
    ("choose_file", "తాళపు పెట్టె నకలు ఫైల్ ఎంచుకోండి."),
    ("added", "పరిచయం చేర్చబడింది"),
    ("saved_prefix", "దాచబడింది"),
];

const PA: &[(&str, &str)] = &[
    ("remove", "ਹਟਾਓ"),
    ("share", "ਸੱਦਾ ਵੰਡੋ"),
    ("paste", "ਸੱਦਾ ਚਿਪਕਾਓ"),
    ("paste_body", "ghalbol:// ਜਾਂ https://ghalbol.com/connect/ ਕੜੀ ਚਿਪਕਾਓ."),
    ("add", "ਜਨਤਕ ਚਾਬੀ ਨਾਲ ਜੋੜੋ"),
    ("add_body", "ਮਹਿਮਾਨ ਮੇਜ਼ਬਾਨ ਦੀ ਜਨਤਕ ਚਾਬੀ ਰੱਖਦਾ ਹੈ. ਮੇਜ਼ਬਾਨ ਨੂੰ ਪਹਿਲਾਂ ਤੁਹਾਡੀ ਚਾਬੀ ਨਹੀਂ ਚਾਹੀਦੀ."),
    ("contacts", "ਸੰਪਰਕ"),
    ("none", "ਅਜੇ ਸੰਪਰਕ ਨਹੀਂ"),
    ("blocked", "ਰੋਕੇ ਹੋਏ"),
    ("blocked_empty", "ਕੋਈ ਰੋਕਿਆ ਨਹੀਂ. ਸੂਚੀ ਵਾਲੇ ਨੂੰ ਰੋਕਣ ਲਈ ਜਨਤਕ ਚਾਬੀ ਚਿਪਕਾਓ."),
    ("delivery", "ਪਹੁੰਚ ਦਾ ਭੰਡਾਰ"),
    ("log", "ਐਪ ਖਾਤਾ"),
    ("key", "ਨਿੱਜੀ ਚਾਬੀ"),
    ("key_body", "ਐਪ ਪਾਸਵਰਡ ਲਿਖੋ ਫਿਰ ਚਾਬੀ ਵਿਖਾਓ. ਸਿਰਫ਼ ਇਕਾਂਤ ਵਿੱਚ."),
    ("backup", "ਨਕਲ ਨਿਰਯਾਤ"),
    ("backup_body", "ਗੁਪਤ ਚਾਬੀਭੰਡਾਰ ਸੰਭਾਲਦਾ ਹੈ. ਦੂਜੇ ਯੰਤਰ ਉੱਤੇ ਖੋਲ੍ਹਣ ਲਈ ਪਾਸਵਰਡ ਚਾਹੀਦਾ."),
    ("password", "ਪਾਸਵਰਡ ਬਦਲੋ"),
    ("password_body", "ਮੌਜੂਦਾ ਪਾਸਵਰਡ ਸੱਦੇ ਦੇ ਖਾਨੇ ਵਿੱਚ. ਨਵਾਂ ਨਾਮ ਦੇ ਖਾਨੇ ਵਿੱਚ. ਪੁਰਾਣੀ ਨਕਲ ਪੁਰਾਣਾ ਪਾਸਵਰਡ ਰੱਖਦੀ ਹੈ."),
    ("about", "ਘਾਲ ਬੋਲ ਬਾਰੇ"),
    ("about_body", "ਸਿਰੇ ਤੋਂ ਸਿਰੇ ਤੱਕ ਗੁਪਤ ਸੁਨੇਹਾ. ਹਰ ਯੰਤਰ ਆਪਣੀ ਗੱਲ ਰੱਖਦਾ ਹੈ."),
    ("no_status", "ਕੋਈ ਹਾਲਤ ਨਹੀਂ"),
    ("save_backup", "ਨਕਲ ਸੰਭਾਲੋ"),
    ("save_backup_body", "ਗੱਲ ਤੋਂ ਪਹਿਲਾਂ ਗੁਪਤ ਨਕਲ ਸੰਭਾਲੋ. ਇਹ ਅਤੇ ਪਾਸਵਰਡ ਨਾ ਹੋਣ ਤਾਂ ਇਹ ਪਛਾਣ ਵਾਪਸ ਨਹੀਂ ਆਉਂਦੀ."),
    ("back", "ਪਿੱਛੇ"),
    ("join_go", "ਜੁੜੋ"),
    ("add_go", "ਸੰਪਰਕ ਜੋੜੋ"),
    ("add_short", "ਜੋੜੋ"),
    ("toggle", "ਰੋਕ ਬਦਲੋ"),
    ("refresh", "ਤਾਜ਼ਾ"),
    ("show_key", "ਚਾਬੀ ਵਿਖਾਓ"),
    ("save", "ਨਕਲ ਸੰਭਾਲੋ"),
    ("change", "ਪਾਸਵਰਡ ਬਦਲੋ"),
    ("save_status", "ਹਾਲਤ ਸੰਭਾਲੋ"),
    ("speaker", "ਸਪੀਕਰ"),
    ("speaker_off", "ਸਪੀਕਰ ਬੰਦ"),
    ("scan_qr", "ਕਿਊਆਰ ਪੜ੍ਹੋ"),
    ("qr_picture", "ਕਿਊਆਰ ਤਸਵੀਰ"),
    ("must_save", "ਅੱਗੇ ਵਧਣ ਤੋਂ ਪਹਿਲਾਂ ਨਕਲ ਸੰਭਾਲੋ."),
    ("enter_password", "ਪਹਿਲਾਂ ਇਸ ਨਕਲ ਦਾ ਪਾਸਵਰਡ ਲਿਖੋ."),
    ("choose_file", "ਚਾਬੀਭੰਡਾਰ ਦੀ ਨਕਲ ਫਾਈਲ ਚੁਣੋ."),
    ("added", "ਸੰਪਰਕ ਜੁੜਿਆ"),
    ("saved_prefix", "ਸੰਭਾਲਿਆ"),
];

const UR: &[(&str, &str)] = &[
    ("remove", "ہٹائیں"),
    ("share", "دعوت بانٹیں"),
    ("paste", "دعوت چسپاں کریں"),
    ("paste_body", "ghalbol:// یا https://ghalbol.com/connect/ ربط چسپاں کریں۔"),
    ("add", "عوامی کلید سے جوڑیں"),
    ("add_body", "مہمان میزبان کی عوامی کلید رکھتا ہے۔ میزبان کو پہلے آپ کی کلید نہیں چاہیے۔"),
    ("contacts", "رابطے"),
    ("none", "ابھی کوئی رابطہ نہیں"),
    ("blocked", "روکے ہوئے"),
    ("blocked_empty", "کوئی رکا نہیں۔ فہرست والے کو روکنے کے لیے عوامی کلید چسپاں کریں۔"),
    ("delivery", "ترسیل کا ذخیرہ"),
    ("log", "ایپ کا کھاتہ"),
    ("key", "نجی کلید"),
    ("key_body", "ایپ کا پاس ورڈ لکھیں پھر کلید دکھائیں۔ صرف تنہائی میں۔"),
    ("backup", "نقل برآمد"),
    ("backup_body", "مرموز کلید خانہ محفوظ کرتا ہے۔ دوسرے آلے پر کھولنے کے لیے پاس ورڈ چاہیے۔"),
    ("password", "پاس ورڈ بدلیں"),
    ("password_body", "موجودہ پاس ورڈ دعوت کے خانے میں۔ نیا نام کے خانے میں۔ پرانی نقل پرانا پاس ورڈ رکھتی ہے۔"),
    ("about", "غال بول کے بارے"),
    ("about_body", "سرے سے سرے تک مرموز پیغام۔ ہر آلہ اپنی گفتگو رکھتا ہے۔"),
    ("no_status", "کوئی حالت نہیں"),
    ("save_backup", "نقل محفوظ کریں"),
    ("save_backup_body", "بات سے پہلے مرموز نقل محفوظ کریں۔ اس کے اور پاس ورڈ کے بغیر یہ شناخت واپس نہیں آتی۔"),
    ("back", "واپس"),
    ("join_go", "شامل ہوں"),
    ("add_go", "رابطہ جوڑیں"),
    ("add_short", "جوڑیں"),
    ("toggle", "روک بدلیں"),
    ("refresh", "تازہ"),
    ("show_key", "کلید دکھائیں"),
    ("save", "نقل محفوظ کریں"),
    ("change", "پاس ورڈ بدلیں"),
    ("save_status", "حالت محفوظ کریں"),
    ("speaker", "اسپیکر"),
    ("speaker_off", "اسپیکر بند"),
    ("scan_qr", "کیو آر پڑھیں"),
    ("qr_picture", "کیو آر تصویر"),
    ("must_save", "آگے بڑھنے سے پہلے نقل محفوظ کریں۔"),
    ("enter_password", "پہلے اس نقل کا پاس ورڈ لکھیں۔"),
    ("choose_file", "کلید خانے کی نقل فائل چنیں۔"),
    ("added", "رابطہ جڑ گیا"),
    ("saved_prefix", "محفوظ ہوا"),
];

const NE: &[(&str, &str)] = &[
    ("remove", "हटाउनुहोस्"),
    ("share", "निमन्त्रणा बाँड्नुहोस्"), ("paste", "निमन्त्रणा टाँस्नुहोस्"),
    ("paste_body", "ghalbol:// वा https://ghalbol.com/connect/ लिंक टाँस्नुहोस्।"),
    ("add", "सार्वजनिक साँचोले थप्नुहोस्"),
    ("add_body", "पाहुनाले आयोजकको सार्वजनिक साँचो राख्छ। आयोजकलाई पहिले तपाईंको साँचो चाहिँदैन।"),
    ("contacts", "सम्पर्क"), ("none", "अहिले सम्पर्क छैन"), ("blocked", "रोकिएका"),
    ("blocked_empty", "कोही रोकिएको छैन। सूचीको मान्छे रोक्न सार्वजनिक साँचो टाँस्नुहोस्।"),
    ("delivery", "पुर्याउने भण्डार"), ("log", "एपको खाता"), ("key", "निजी साँचो"),
    ("key_body", "एपको पासवर्ड लेखेर साँचो देखाउनुहोस्। एकान्तमा मात्र।"),
    ("backup", "प्रतिलिपि निर्यात"),
    ("backup_body", "गुप्त साँचोभण्डार बचत गर्छ। अर्को यन्त्रमा खोल्न पासवर्ड चाहिन्छ।"),
    ("password", "पासवर्ड बदल्नुहोस्"),
    ("password_body", "हालको पासवर्ड निमन्त्रणाको कोठामा। नयाँ नामको कोठामा। पुरानो प्रतिलिपि पुरानो पासवर्ड राख्छ।"),
    ("about", "घाल बोल बारे"),
    ("about_body", "छेउदेखि छेउसम्म गुप्त सन्देश। प्रत्येक यन्त्र आफ्नो कुरा राख्छ।"),
    ("no_status", "कुनै अवस्था छैन"), ("save_backup", "प्रतिलिपि बचत गर्नुहोस्"),
    ("save_backup_body", "कुरा गर्नुअघि गुप्त प्रतिलिपि बचत गर्नुहोस्। यो र पासवर्ड नभए यो पहिचान फर्किँदैन।"),
    ("back", "पछाडि"), ("join_go", "सामेल हुनुहोस्"), ("add_go", "सम्पर्क थप्नुहोस्"),
    ("add_short", "थप्नुहोस्"), ("toggle", "रोक बदल्नुहोस्"), ("refresh", "ताजा"),
    ("show_key", "साँचो देखाउनुहोस्"), ("save", "प्रतिलिपि बचत"), ("change", "पासवर्ड बदल्नुहोस्"),
    ("save_status", "अवस्था बचत"), ("speaker", "स्पिकर"), ("speaker_off", "स्पिकर बन्द"),
    ("scan_qr", "क्यूआर पढ्नुहोस्"), ("qr_picture", "क्यूआर चित्र"),
    ("must_save", "अघि बढ्नुअघि प्रतिलिपि बचत गर्नुहोस्।"),
    ("enter_password", "पहिले यो प्रतिलिपिको पासवर्ड लेख्नुहोस्।"),
    ("choose_file", "साँचोभण्डारको प्रतिलिपि फाइल छान्नुहोस्।"),
    ("added", "सम्पर्क थपियो"), ("saved_prefix", "बचत भयो"),
];

const OR: &[(&str, &str)] = &[
    ("remove", "ହଟାନ୍ତୁ"),
    ("share", "ନିମନ୍ତ୍ରଣ ବାଣ୍ଟନ୍ତୁ"), ("paste", "ନିମନ୍ତ୍ରଣ ଲଗାନ୍ତୁ"),
    ("paste_body", "ghalbol:// କିମ୍ବା https://ghalbol.com/connect/ ଲିଙ୍କ ଲଗାନ୍ତୁ।"),
    ("add", "ସାର୍ବଜନୀନ ଚାବିରେ ଯୋଡ଼ନ୍ତୁ"),
    ("add_body", "ଅତିଥି ଆୟୋଜକଙ୍କ ସାର୍ବଜନୀନ ଚାବି ରଖନ୍ତି। ଆୟୋଜକଙ୍କୁ ଆଗରୁ ଆପଣଙ୍କ ଚାବି ଲାଗେ ନାହିଁ।"),
    ("contacts", "ସମ୍ପର୍କ"), ("none", "ଏଯାଏ ସମ୍ପର୍କ ନାହିଁ"), ("blocked", "ଅଟକାଯାଇଥିବା"),
    ("blocked_empty", "କେହି ଅଟକାଯାଇ ନାହାନ୍ତି। ତାଲିକାର ଲୋକଙ୍କୁ ଅଟକାଇବାକୁ ସାର୍ବଜନୀନ ଚାବି ଲଗାନ୍ତୁ।"),
    ("delivery", "ପହଞ୍ଚର ଭଣ୍ଡାର"), ("log", "ଆପ ଖାତା"), ("key", "ବ୍ୟକ୍ତିଗତ ଚାବି"),
    ("key_body", "ଆପ ପାସୱାର୍ଡ ଲେଖି ଚାବି ଦେଖାନ୍ତୁ। କେବଳ ଏକାନ୍ତରେ।"),
    ("backup", "ନକଲ ରପ୍ତାନି"),
    ("backup_body", "ସଂକେତିତ ଚାବିଭଣ୍ଡାର ସାଇତେ। ଅନ୍ୟ ଯନ୍ତ୍ରରେ ଖୋଲିବାକୁ ପାସୱାର୍ଡ ଲାଗେ।"),
    ("password", "ପାସୱାର୍ଡ ବଦଳାନ୍ତୁ"),
    ("password_body", "ବର୍ତ୍ତମାନ ପାସୱାର୍ଡ ନିମନ୍ତ୍ରଣ ଘରେ। ନୂଆ ନାମ ଘରେ। ପୁରୁଣା ନକଲ ପୁରୁଣା ପାସୱାର୍ଡ ରଖେ।"),
    ("about", "ଘାଲ ବୋଲ ବିଷୟରେ"),
    ("about_body", "ପ୍ରାନ୍ତରୁ ପ୍ରାନ୍ତ ସଂକେତିତ ସନ୍ଦେଶ। ପ୍ରତି ଯନ୍ତ୍ର ନିଜ କଥା ରଖେ।"),
    ("no_status", "କୌଣସି ଅବସ୍ଥା ନାହିଁ"), ("save_backup", "ନକଲ ସାଇତନ୍ତୁ"),
    ("save_backup_body", "କଥା ଆଗରୁ ସଂକେତିତ ନକଲ ସାଇତନ୍ତୁ। ଏହା ଓ ପାସୱାର୍ଡ ନଥିଲେ ଏହି ପରିଚୟ ଫେରେ ନାହିଁ।"),
    ("back", "ପଛକୁ"), ("join_go", "ଯୋଗ ଦିଅନ୍ତୁ"), ("add_go", "ସମ୍ପର୍କ ଯୋଡ଼ନ୍ତୁ"),
    ("add_short", "ଯୋଡ଼ନ୍ତୁ"), ("toggle", "ଅଟକ ବଦଳାନ୍ତୁ"), ("refresh", "ସତେଜ"),
    ("show_key", "ଚାବି ଦେଖାନ୍ତୁ"), ("save", "ନକଲ ସାଇତନ୍ତୁ"), ("change", "ପାସୱାର୍ଡ ବଦଳାନ୍ତୁ"),
    ("save_status", "ଅବସ୍ଥା ସାଇତନ୍ତୁ"), ("speaker", "ସ୍ପିକର"), ("speaker_off", "ସ୍ପିକର ବନ୍ଦ"),
    ("scan_qr", "କ୍ୟୁଆର ପଢ଼ନ୍ତୁ"), ("qr_picture", "କ୍ୟୁଆର ଚିତ୍ର"),
    ("must_save", "ଆଗକୁ ଯିବା ଆଗରୁ ନକଲ ସାଇତନ୍ତୁ।"),
    ("enter_password", "ପ୍ରଥମେ ଏହି ନକଲର ପାସୱାର୍ଡ ଲେଖନ୍ତୁ।"),
    ("choose_file", "ଚାବିଭଣ୍ଡାରର ନକଲ ଫାଇଲ ବାଛନ୍ତୁ।"),
    ("added", "ସମ୍ପର୍କ ଯୋଡ଼ାଗଲା"), ("saved_prefix", "ସାଇତାଗଲା"),
];

const SA: &[(&str, &str)] = &[
    ("remove", "अपाकरोतु"),
    ("share", "आमन्त्रणं विभजस्व"), ("paste", "आमन्त्रणं योजय"),
    ("paste_body", "ghalbol:// अथवा https://ghalbol.com/connect/ सूत्रं योजय।"),
    ("add", "सार्वजनिककुञ्जिकया योजय"),
    ("add_body", "अतिथिः आयोजकस्य सार्वजनिककुञ्जिकां धारयति। आयोजकाय पूर्वं तव कुञ्जिका न अपेक्ष्यते।"),
    ("contacts", "सम्पर्काः"), ("none", "अद्यापि सम्पर्काः न सन्ति"), ("blocked", "निरुद्धाः"),
    ("blocked_empty", "कोऽपि निरुद्धः नास्ति। सूच्याः जनं निरोद्धुं सार्वजनिककुञ्जिकां योजय।"),
    ("delivery", "प्रेषणभाण्डारम्"), ("log", "अनुप्रयोगवृत्तान्तः"), ("key", "गुप्तकुञ्जिका"),
    ("key_body", "अनुप्रयोगगुप्तशब्दं लिखित्वा कुञ्जिकां दर्शय। केवलं विजने।"),
    ("backup", "प्रतिकृतिं निर्यापय"),
    ("backup_body", "गुप्तां कुञ्जिकापेटीं रक्षति। अन्ययन्त्रे उद्घाटयितुं गुप्तशब्दः अपेक्ष्यते।"),
    ("password", "गुप्तशब्दं परिवर्तय"),
    ("password_body", "वर्तमानगुप्तशब्दः आमन्त्रणकोष्ठके। नूतनः नामकोष्ठके। पुरातना प्रतिकृतिः पुरातनं गुप्तशब्दं धारयति।"),
    ("about", "घालबोलविषये"),
    ("about_body", "अन्तादन्तं गुप्तसन्देशः। प्रत्येकं यन्त्रं स्वां कथां धारयति।"),
    ("no_status", "अवस्था नास्ति"), ("save_backup", "प्रतिकृतिं रक्ष"),
    ("save_backup_body", "संलापात् पूर्वं गुप्तां प्रतिकृतिं रक्ष। अनया गुप्तशब्देन च विना इयं परिचयः न प्रत्यागच्छति।"),
    ("back", "पश्चात्"), ("join_go", "संगच्छ"), ("add_go", "सम्पर्कं योजय"),
    ("add_short", "योजय"), ("toggle", "निरोधं परिवर्तय"), ("refresh", "नवीकुरु"),
    ("show_key", "कुञ्जिकां दर्शय"), ("save", "प्रतिकृतिं रक्ष"), ("change", "गुप्तशब्दं परिवर्तय"),
    ("save_status", "अवस्थां रक्ष"), ("speaker", "ध्वनिवर्धकः"), ("speaker_off", "ध्वनिवर्धकः निरुद्धः"),
    ("scan_qr", "क्यूआरं पठ"), ("qr_picture", "क्यूआरचित्रम्"),
    ("must_save", "अग्रे गन्तुं पूर्वं प्रतिकृतिं रक्ष।"),
    ("enter_password", "प्रथमम् अस्याः प्रतिकृतेः गुप्तशब्दं लिख।"),
    ("choose_file", "कुञ्जिकापेट्याः प्रतिकृतिसञ्चिकां चिनु।"),
    ("added", "सम्पर्कः योजितः"), ("saved_prefix", "रक्षितम्"),
];

const KS: &[(&str, &str)] = &[
    ("remove", "ہٹٲیوٗ"),
    ("share", "دعوت بانٹِو"), ("paste", "دعوت چِپکٲوِو"),
    ("paste_body", "ghalbol:// یا https://ghalbol.com/connect/ لنک چِپکٲوِو۔"),
    ("add", "عوامی چابی سٕتۍ جوڑِو"),
    ("add_body", "مهمان میزبانٕچ عوامی چابی تھاوان چھُ۔ میزبانس گۄڈٕ چھُ نَہ تُہٕنٛز چابی ضروٗرت۔"),
    ("contacts", "رابطہٕ"), ("none", "وۄنۍ چھُ نَہ کانہہ رابطہ"), ("blocked", "رُکاوِت"),
    ("blocked_empty", "کانہہ چھُ نَہ رُکاوِت۔ فہرستٕکِس رُکاونَس عوامی چابی چِپکٲوِو۔"),
    ("delivery", "پہنچُک بھنڈار"), ("log", "ایپ ہِساب"), ("key", "نجی چابی"),
    ("key_body", "ایپ پاسوَرڈ لؠکھِو پتہٕ چابی ہٲوِو۔ صرف تنہٲیی منٛز۔"),
    ("backup", "نقل برآمد"),
    ("backup_body", "پوشیدٕ چابی خانہٕ محفوظ کران چھُ۔ بیٚیِس آلَس پؠٹھ کھولَنَس پاسوَرڈ چھُ ضروٗرت۔"),
    ("password", "پاسوَرڈ بدلٲوِو"),
    ("password_body", "موجودٕ پاسوَرڈ دعوتٕکِس خانَس منٛز۔ نُو ناوٕکِس خانَس منٛز۔ پرون نقل پرون پاسوَرڈ تھاوان چھِ۔"),
    ("about", "غال بول مُتعَلِق"),
    ("about_body", "سرٕ پؠٹھ سرَس تام پوشیدٕ پٲغام۔ ہر آلہٕ پنٕنۍ کَتھ تھاوان چھُ۔"),
    ("no_status", "کانہہ حالت چھُ نَہ"), ("save_backup", "نقل محفوظ کٔرِو"),
    ("save_backup_body", "کَتھ برۄنہہ پوشیدٕ نقل محفوظ کٔرِو۔ یِمَے تہٕ پاسوَرڈَس بغیر یِہ پہچان واپَس یِوان چھُ نَہ۔"),
    ("back", "واپس"), ("join_go", "شٲمِل گژھِو"), ("add_go", "رابطہ جوڑِو"),
    ("add_short", "جوڑِو"), ("toggle", "رُکاوٹ بدلٲوِو"), ("refresh", "تازٕ"),
    ("show_key", "چابی ہٲوِو"), ("save", "نقل محفوظ"), ("change", "پاسوَرڈ بدلٲوِو"),
    ("save_status", "حالت محفوظ"), ("speaker", "اسپیکر"), ("speaker_off", "اسپیکر بند"),
    ("scan_qr", "کیو آر پٔرِو"), ("qr_picture", "کیو آر تصویر"),
    ("must_save", "برۄنہہ نقل محفوظ کٔرِو۔"),
    ("enter_password", "گۄڈٕ یِم نقلُک پاسوَرڈ لؠکھِو۔"),
    ("choose_file", "چابی خانٕچ نقل فایل چُنِو۔"),
    ("added", "رابطہ جوڑِت"), ("saved_prefix", "محفوظ"),
];

const SD: &[(&str, &str)] = &[
    ("remove", "هٽايو"),
    ("share", "دعوت ونڊيو"), ("paste", "دعوت چنبڙايو"),
    ("paste_body", "ghalbol:// يا https://ghalbol.com/connect/ ڳنڍڻو چنبڙايو."),
    ("add", "عوامي چاٻي سان جوڙيو"),
    ("add_body", "مهمان ميزبان جي عوامي چاٻي رکي ٿو. ميزبان کي پهريان اوھان جي چاٻي نٿي کپي."),
    ("contacts", "رابطا"), ("none", "اڃا رابطا ناهن"), ("blocked", "روڪيل"),
    ("blocked_empty", "ڪو به روڪيل ناهي. فهرست واري کي روڪڻ لاءِ عوامي چاٻي چنبڙايو."),
    ("delivery", "پهچ جو ڀنڊار"), ("log", "ايپ کاتو"), ("key", "نجي چاٻي"),
    ("key_body", "ايپ پاسورڊ لکي پوءِ چاٻي ڏيکاريو. رڳو اڪيلائي ۾."),
    ("backup", "نقل برآمد"),
    ("backup_body", "ڳجھو چاٻي خانو محفوظ ڪري ٿو. ٻئي اوزار تي کولڻ لاءِ پاسورڊ کپي."),
    ("password", "پاسورڊ بدلايو"),
    ("password_body", "هاڻوڪو پاسورڊ دعوت جي خاني ۾. نئون نالي جي خاني ۾. پراڻي نقل پراڻو پاسورڊ رکي ٿي."),
    ("about", "غال بول بابت"),
    ("about_body", "ڇيڙي کان ڇيڙي تائين ڳجھو نياپو. هر اوزار پنهنجي ڳالهه رکي ٿو."),
    ("no_status", "ڪا حالت ناهي"), ("save_backup", "نقل محفوظ ڪريو"),
    ("save_backup_body", "ڳالهه کان اڳ ڳجهي نقل محفوظ ڪريو. هن ۽ پاسورڊ کان سواءِ هي سڃاڻپ واپس نٿي اچي."),
    ("back", "پوئتي"), ("join_go", "شامل ٿيو"), ("add_go", "رابطو جوڙيو"),
    ("add_short", "جوڙيو"), ("toggle", "روڪ بدلايو"), ("refresh", "تازو"),
    ("show_key", "چاٻي ڏيکاريو"), ("save", "نقل محفوظ"), ("change", "پاسورڊ بدلايو"),
    ("save_status", "حالت محفوظ"), ("speaker", "اسپيڪر"), ("speaker_off", "اسپيڪر بند"),
    ("scan_qr", "ڪيو آر پڙهو"), ("qr_picture", "ڪيو آر تصوير"),
    ("must_save", "اڳتي وڌڻ کان اڳ نقل محفوظ ڪريو."),
    ("enter_password", "پهريان هن نقل جو پاسورڊ لکو."),
    ("choose_file", "چاٻي خاني جي نقل فائل چونڊيو."),
    ("added", "رابطو جڙي ويو"), ("saved_prefix", "محفوظ ٿيو"),
];

macro_rules! sheet {
    ($($k:literal => $v:literal),* $(,)?) => { &[ $(($k, $v)),* ] };
}

const BRX: &[(&str, &str)] = sheet![
    "remove" => "बोखां",
    "share" => "निमन्त्रण रान", "paste" => "निमन्त्रण नांजाब",
    "paste_body" => "ghalbol:// एबा https://ghalbol.com/connect/ लिंक नांजाब।",
    "add" => "सार्वजनिक साबिजों दाजाब",
    "add_body" => "दावबो गिबिमावनि सार्वजनिक साबि दोन। गिबिमावाव सिगां नोंनि साबि गोनां नङा।",
    "contacts" => "सुबुं", "none" => "दाबाव सुबुं गैया", "blocked" => "होबथानाय",
    "blocked_empty" => "सासेबो होबथानाय गैया। लिस्टनि मानसिखौ होबथानो सार्वजनिक साबि नांजाब।",
    "delivery" => "सोलोंथाइनि बख्रि", "log" => "एप खथा", "key" => "गावारि साबि",
    "key_body" => "एप पासवर्ड लिरनानै साबि दिनथि। लांदाङैयावलो।",
    "backup" => "नकल दैथाय हर",
    "backup_body" => "गुप्त साबि बख्रि दोन। गुबुन आयजैयाव खेवनो पासवर्ड गोनां।",
    "password" => "पासवर्ड सोलाय",
    "password_body" => "दा नि पासवर्ड निमन्त्रणनि खथियाव। गोदानखौ मुंनि खथियाव। गोजाम नकलआ गोजाम पासवर्ड दोन।",
    "about" => "घाल बोलनि सोमोन्दै",
    "about_body" => "मुदाफोरनिफ्राय मुदाफोराव गुप्त खौरां। आयजै मानिया गावनि खौरां दोन।",
    "no_status" => "थाखि गैया", "save_backup" => "नकल दोन",
    "save_backup_body" => "खौरांनि सिगां गुप्त नकल दोन। बे आरो पासवर्ड गैयाब्ला बे सिनायथि फैफिननाय नङा।",
    "back" => "उनथिं", "join_go" => "सोलाय", "add_go" => "सुबुं दाजाब",
    "add_short" => "दाजाब", "toggle" => "होबथा सोलाय", "refresh" => "गोदान खालाम",
    "show_key" => "साबि दिनथि", "save" => "नकल दोन", "change" => "पासवर्ड सोलाय",
    "save_status" => "थाखि दोन", "speaker" => "सारांखुंगा", "speaker_off" => "सारांखुंगा बन्द",
    "scan_qr" => "क्यूआर फराय", "qr_picture" => "क्यूआर सावगारि",
    "must_save" => "दावगानो नकल दोन।",
    "enter_password" => "सिगां बे नकलनि पासवर्ड लिर।",
    "choose_file" => "साबि बख्रिनि नकल फाइल सायख।",
    "added" => "सुबुं दाजाबबाय", "saved_prefix" => "दोनबाय",
];

const DOI: &[(&str, &str)] = sheet![
    "remove" => "हटाओ",
    "share" => "नेवता बांडो", "paste" => "नेवता चिपकाओ",
    "paste_body" => "ghalbol:// जां https://ghalbol.com/connect/ लिंक चिपकाओ।",
    "add" => "सार्वजनिक चाबी कन्नै जोड़ो",
    "add_body" => "मेहमान मेजबान दी सार्वजनिक चाबी रखदा ऐ। मेजबान गी पैह्‌लें तुंदी चाबी दी लोड़ नेईं।",
    "contacts" => "संपर्क", "none" => "अजें संपर्क नेईं", "blocked" => "रोके दे",
    "blocked_empty" => "कोई रोकेआ नेईं। सूची चले गी रोकने लेई सार्वजनिक चाबी चिपकाओ।",
    "delivery" => "पंहुंच दा भंडार", "log" => "ऐप खाता", "key" => "नीजी चाबी",
    "key_body" => "ऐप पासवर्ड लिखी चाबी दस्सो। सिर्फ तन्हाई च।",
    "backup" => "नकल निर्यात",
    "backup_body" => "गुप्त चाबीभंडार सम्भालदा ऐ। दूजे यंत्र उप्पर खोलने लेई पासवर्ड लोड़दा ऐ।",
    "password" => "पासवर्ड बदलो",
    "password_body" => "हुण दा पासवर्ड नेवते दे खाने च। नमां नाम दे खाने च। पुरानी नकल पुराना पासवर्ड रखदी ऐ।",
    "about" => "घाल बोल बारे",
    "about_body" => "सिरे थमां सिरे तगर गुप्त सन्नेहा। हर यंत्र अपनी गल्ल रखदा ऐ।",
    "no_status" => "कोई हालत नेईं", "save_backup" => "नकल सम्भालो",
    "save_backup_body" => "गल्ल थमां पैह्‌लें गुप्त नकल सम्भालो। इस ते पासवर्ड दे बगैर एह् पछान वापस नेईं औंदी।",
    "back" => "पिच्छें", "join_go" => "जुड़ो", "add_go" => "संपर्क जोड़ो",
    "add_short" => "जोड़ो", "toggle" => "रोक बदलो", "refresh" => "ताजा",
    "show_key" => "चाबी दस्सो", "save" => "नकल सम्भालो", "change" => "पासवर्ड बदलो",
    "save_status" => "हालत सम्भालो", "speaker" => "स्पिकर", "speaker_off" => "स्पिकर बंद",
    "scan_qr" => "क्यूआर पढ़ो", "qr_picture" => "क्यूआर तस्वीर",
    "must_save" => "अग्गें बधने थमां पैह्‌लें नकल सम्भालो।",
    "enter_password" => "पैह्‌लें इस नकल दा पासवर्ड लिखो।",
    "choose_file" => "चाबीभंडार दी नकल फाइल चुनो।",
    "added" => "संपर्क जुड़या", "saved_prefix" => "सम्भालेआ",
];

const KOK: &[(&str, &str)] = sheet![
    "remove" => "काडचें",
    "share" => "आमन्त्रण वांट", "paste" => "आमन्त्रण चिकटाई",
    "paste_body" => "ghalbol:// वा https://ghalbol.com/connect/ दुवो चिकटाई।",
    "add" => "सार्वजनिक चावीन जोड",
    "add_body" => "पाहुणो यजमानाची सार्वजनिक चावी दवरता। यजमानाक पयलीं तुमची चावी जाय ना।",
    "contacts" => "संपर्क", "none" => "आनी संपर्क नात", "blocked" => "आडायिल्ले",
    "blocked_empty" => "कोण आडायिल्लो ना। वळेरेंतल्या मनीसाक आडावपाक सार्वजनिक चावी चिकटाई।",
    "delivery" => "पावपाचें कोठार", "log" => "एप खातें", "key" => "खाजगी चावी",
    "key_body" => "एप पासवर्ड बरोवन चावी दाखयात। फकत एकांतांत।",
    "backup" => "प्रत निर्यात",
    "backup_body" => "गुप्त चावीकोठार सांबाळटा। दुसऱ्या यंत्रार उगडपाक पासवर्ड जाय।",
    "password" => "पासवर्ड बदलात",
    "password_body" => "सद्याचो पासवर्ड आमन्त्रणाच्या खोळ्यांत। नवो नावाच्या खोळ्यांत। पोन्न्या प्रतीक पोन्नो पासवर्ड उरता।",
    "about" => "घाल बोल विशीं",
    "about_body" => "शेवटासावन शेवटा मेरेन गुप्त निरोप। दर यंत्र आपली गजाल दवरता।",
    "no_status" => "स्थिती ना", "save_backup" => "प्रत सांबाळात",
    "save_backup_body" => "उलोवचे पयलीं गुप्त प्रत सांबाळात। ही आनी पासवर्ड ना जाल्यार ही वळख परत येना।",
    "back" => "फाटीं", "join_go" => "जोडचे", "add_go" => "संपर्क जोडात",
    "add_short" => "जोडात", "toggle" => "आडावो बदलात", "refresh" => "ताजें",
    "show_key" => "चावी दाखयात", "save" => "प्रत सांबाळात", "change" => "पासवर्ड बदलात",
    "save_status" => "स्थिती सांबाळात", "speaker" => "ध्वनिवर्धक", "speaker_off" => "ध्वनिवर्धक बंद",
    "scan_qr" => "क्यूआर वाचात", "qr_picture" => "क्यूआर चित्र",
    "must_save" => "फुडें वचचे पयलीं प्रत सांबाळात।",
    "enter_password" => "पयलीं हे प्रतीचो पासवर्ड बरोयात।",
    "choose_file" => "चावीकोठाराची प्रत फायल वेंचात।",
    "added" => "संपर्क जोडलो", "saved_prefix" => "सांबाळलें",
];

const MNI: &[(&str, &str)] = sheet![
    "remove" => "ꯂꯧꯊꯣꯛꯄ",
    "share" => "ইনভিটেশন শেয়ার তৌ", "paste" => "ইনভিটেশন নমথৌ",
    "paste_body" => "ghalbol:// নত্ত্রগা https://ghalbol.com/connect/ লিংক নমথৌ।",
    "add" => "পব্লিক কিদা হাপচিনবা",
    "add_body" => "গেস্টনা হোস্টকি পব্লিক কি থম্মি। হোস্টনা মমাংদা নহাক্কি কি মথৌই।",
    "contacts" => "কন্ট্যাক্ট", "none" => "হৌজিক ফাউবা কন্ট্যাক্ট লৈতে", "blocked" => "থিংবা",
    "blocked_empty" => "কনা থিংদে। লিস্টকি মী থিংনবা পব্লিক কি নমথৌ।",
    "delivery" => "থংবা মচাও", "log" => "এপকি খুদোল", "key" => "প্রাইভেট কি",
    "key_body" => "এপ পাসৱার্দ ইবা অমত্তা কি উৎপা। অচৌবা মফমদা খক্তং।",
    "backup" => "বেকআপ থোকপা",
    "backup_body" => "এনক্রিপ্ট তৌবা কি মচাও থম্মি। অতৈ মশিনদা হাংনবা পাসৱার্দ মথৌ।",
    "password" => "পাসৱার্দ হোংবা",
    "password_body" => "হৌজিক্কি পাসৱার্দ ইনভিটেশনগি মফমদা। অনৌবা মিংগি মফমদা। অরিবা বেকআপনা অরিবা পাসৱার্দ থম্মি।",
    "about" => "ঘাল বোলগি মরমদা",
    "about_body" => "মনুংদগী মপানদা এনক্রিপ্ট তৌবা পাউ। মশিন খুদিংমক্না মশাগি ৱারি থম্মি।",
    "no_status" => "স্টেটস লৈতে", "save_backup" => "বেকআপ থম্মু",
    "save_backup_body" => "ৱারি ঙাংবা মমাংদা এনক্রিপ্ট তৌবা বেকআপ থম্মু। মসি অমসুং পাসৱার্দ লৈত্রবদি মসিগি আইডি হল্লকতে।",
    "back" => "মনুং", "join_go" => "শরুক য়াবা", "add_go" => "কন্ট্যাক্ট হাপচিনবা",
    "add_short" => "হাপচিনবা", "toggle" => "থিংবা হোংবা", "refresh" => "অনৌবা তৌবা",
    "show_key" => "কি উৎপা", "save" => "বেকআপ থম্মু", "change" => "পাসৱার্দ হোংবা",
    "save_status" => "স্টেটস থম্মু", "speaker" => "স্পিকর", "speaker_off" => "স্পিকর থিংবা",
    "scan_qr" => "কিউআর পাবা", "qr_picture" => "কিউআর মমি",
    "must_save" => "মখা চত্থবা মমাংদা বেকআপ থম্মু।",
    "enter_password" => "মমাংদা মসিগি বেকআপকি পাসৱার্দ ইয়ু।",
    "choose_file" => "কি মচাওগি বেকআপ ফাইল খনবা।",
    "added" => "কন্ট্যাক্ট হাপচিল্লে", "saved_prefix" => "থম্লে",
];

const MAI: &[(&str, &str)] = sheet![
    "remove" => "हटाउ",
    "share" => "निमंत्रण बांटू", "paste" => "निमंत्रण चिपकाउ",
    "paste_body" => "ghalbol:// वा https://ghalbol.com/connect/ लिंक चिपकाउ।",
    "add" => "सार्वजनिक चाभी सँ जोड़ू",
    "add_body" => "पाहुन यजमानक सार्वजनिक चाभी राखैत अछि। यजमानकेँ पहिने अहाँक चाभी नहि चाही।",
    "contacts" => "संपर्क", "none" => "एखन संपर्क नहि", "blocked" => "रोकल",
    "blocked_empty" => "केओ रोकल नहि। सूचीक लोककेँ रोकबाक लेल सार्वजनिक चाभी चिपकाउ।",
    "delivery" => "पहुँचक भंडार", "log" => "एप खाता", "key" => "निजी चाभी",
    "key_body" => "एप पासवर्ड लिखि चाभी देखाउ। एकांते मात्र।",
    "backup" => "नकल निर्यात",
    "backup_body" => "गुप्त चाभीभंडार बचबैत अछि। दोसर यंत्र पर खोलबाक लेल पासवर्ड चाही।",
    "password" => "पासवर्ड बदलू",
    "password_body" => "एखन पासवर्ड निमंत्रणक खाना मे। नव नामक खाना मे। पुरान नकल पुरान पासवर्ड राखैत अछि।",
    "about" => "घाल बोल विषय मे",
    "about_body" => "छोर सँ छोर धरि गुप्त संदेश। प्रत्येक यंत्र अपन बात राखैत अछि।",
    "no_status" => "कोनो अवस्था नहि", "save_backup" => "नकल बचाउ",
    "save_backup_body" => "बात सँ पहिने गुप्त नकल बचाउ। ई आ पासवर्ड नहि रहला पर ई पहचान घुरि नहि अबैत अछि।",
    "back" => "पाछाँ", "join_go" => "जोड़ू", "add_go" => "संपर्क जोड़ू",
    "add_short" => "जोड़ू", "toggle" => "रोक बदलू", "refresh" => "ताजा",
    "show_key" => "चाभी देखाउ", "save" => "नकल बचाउ", "change" => "पासवर्ड बदलू",
    "save_status" => "अवस्था बचाउ", "speaker" => "स्पिकर", "speaker_off" => "स्पिकर बंद",
    "scan_qr" => "क्यूआर पढ़ू", "qr_picture" => "क्यूआर चित्र",
    "must_save" => "आगाँ बढ़बा सँ पहिने नकल बचाउ।",
    "enter_password" => "पहिने एहि नकलक पासवर्ड लिखू।",
    "choose_file" => "चाभीभंडारक नकल फाइल चुनू।",
    "added" => "संपर्क जोड़ल गेल", "saved_prefix" => "बचल",
];

const SAT: &[(&str, &str)] = sheet![
    "remove" => "ᱚᱪᱚᱜ",
    "share" => "आमंत्रण हाटिञ", "paste" => "आमंत्रण लागाव",
    "paste_body" => "ghalbol:// बा https://ghalbol.com/connect/ लिंक लागाव।",
    "add" => "सार्वजनिक चाबी ते जोड़ाव",
    "add_body" => "पाहुना होड़वाक् सार्वजनिक चाबी दोहोया। होड़वा दो आलेक् चाबी आलेक बाङ लागोक।",
    "contacts" => "संपर्क", "none" => "नितोक् संपर्क बानुक्", "blocked" => "आकोट",
    "blocked_empty" => "ओकोय आकोट बानुक्। सूची रे होड़ आकोट लागित् सार्वजनिक चाबी लागाव।",
    "delivery" => "सेतेर भंडार", "log" => "एप खाता", "key" => "निजी चाबी",
    "key_body" => "एप पासवर्ड ओल ते चाबी उदुक्। एकला रे गे।",
    "backup" => "नकल बाहर",
    "backup_body" => "गुप्त चाबी भंडार दोहोया। एटा मशीन रे झिज लागित् पासवर्ड लागोक।",
    "password" => "पासवर्ड बोदोल",
    "password_body" => "नितोक् पासवर्ड आमंत्रण खाता रे। नावा ञुतुम खाता रे। मारां नकल मारां पासवर्ड दोहोया।",
    "about" => "घाल बोल बारे",
    "about_body" => "मुचा खोन् मुचा गुप्त खोबोर। जान मशीन आपनार कथा दोहोया।",
    "no_status" => "हालत बानुक्", "save_backup" => "नकल दोहोय",
    "save_backup_body" => "कथा आलेक गुप्त नकल दोहोय। नोवा आर पासवर्ड बानुक् रे नोवा चिन्ह रुवाड़ बाङ होयोक्।",
    "back" => "तायोम", "join_go" => "जोड़ोक", "add_go" => "संपर्क जोड़ाव",
    "add_short" => "जोड़ाव", "toggle" => "आकोट बोदोल", "refresh" => "नावा",
    "show_key" => "चाबी उदुक्", "save" => "नकल दोहोय", "change" => "पासवर्ड बोदोल",
    "save_status" => "हालत दोहोय", "speaker" => "सारां पेटी", "speaker_off" => "सारां पेटी बोंदो",
    "scan_qr" => "क्यूआर पढ़ाव", "qr_picture" => "क्यूआर चिताड़",
    "must_save" => "सामेत् आलेक नकल दोहोय।",
    "enter_password" => "आलेक नोवा नकल रेयाक् पासवर्ड ओल।",
    "choose_file" => "चाबी भंडार रेयाक् नकल फाइल बाछाव।",
    "added" => "संपर्क जोड़ोयेना", "saved_prefix" => "दोहोयेना",
];

const BHO: &[(&str, &str)] = sheet![
    "remove" => "हटाईं",
    "share" => "निमंत्रण बाँटीं", "paste" => "निमंत्रण चिपकाईं",
    "paste_body" => "ghalbol:// भा https://ghalbol.com/connect/ लिंक चिपकाईं।",
    "add" => "सार्वजनिक चाभी से जोड़ीं",
    "add_body" => "मेहमान मेजबान के सार्वजनिक चाभी राखेला। मेजबान के पहिले राउर चाभी नइखे चाही।",
    "contacts" => "संपर्क", "none" => "अभी संपर्क नइखे", "blocked" => "रोकल",
    "blocked_empty" => "केहु रोकल नइखे। सूची के आदमी रोके खातिर सार्वजनिक चाभी चिपकाईं।",
    "delivery" => "पहुँच के भंडार", "log" => "ऐप खाता", "key" => "निजी चाभी",
    "key_body" => "ऐप पासवर्ड लिखीं चाभी देखाईं। खाली एकांत में।",
    "backup" => "नकल निर्यात",
    "backup_body" => "गुप्त चाभीभंडार बचावेला। दोसरा यंत्र पर खोले खातिर पासवर्ड चाही।",
    "password" => "पासवर्ड बदलीं",
    "password_body" => "अबके पासवर्ड निमंत्रण के खाना में। नया नाम के खाना में। पुरान नकल पुरान पासवर्ड राखेले।",
    "about" => "घाल बोल बारे",
    "about_body" => "छोर से छोर गुप्त संदेश। हर यंत्र आपन बात राखेला।",
    "no_status" => "कउनो हालत नइखे", "save_backup" => "नकल बचाईं",
    "save_backup_body" => "बात से पहिले गुप्त नकल बचाईं। ई आ पासवर्ड ना रहे त ई पहचान लौटे ना।",
    "back" => "पाछे", "join_go" => "जुड़ीं", "add_go" => "संपर्क जोड़ीं",
    "add_short" => "जोड़ीं", "toggle" => "रोक बदलीं", "refresh" => "ताजा",
    "show_key" => "चाभी देखाईं", "save" => "नकल बचाईं", "change" => "पासवर्ड बदलीं",
    "save_status" => "हालत बचाईं", "speaker" => "स्पिकर", "speaker_off" => "स्पिकर बंद",
    "scan_qr" => "क्यूआर पढ़ीं", "qr_picture" => "क्यूआर फोटो",
    "must_save" => "आगे बढ़े से पहिले नकल बचाईं।",
    "enter_password" => "पहिले ई नकल के पासवर्ड लिखीं।",
    "choose_file" => "चाभीभंडार के नकल फाइल चुनीं।",
    "added" => "संपर्क जुड़ल", "saved_prefix" => "बचल",
];

const HNE: &[(&str, &str)] = sheet![
    "remove" => "हटाव",
    "share" => "नेवता बांट", "paste" => "नेवता चिपकाव",
    "paste_body" => "ghalbol:// या https://ghalbol.com/connect/ लिंक चिपकाव।",
    "add" => "सार्वजनिक चाबी ले जोड़",
    "add_body" => "मेहमान मेजबान के सार्वजनिक चाबी रखथे। मेजबान ला पहिली तोर चाबी नइ चाही।",
    "contacts" => "संपर्क", "none" => "अभी संपर्क नइ हे", "blocked" => "रोके",
    "blocked_empty" => "कोनो रोके नइ हे। सूची के मनखे ला रोके बर सार्वजनिक चाबी चिपकाव।",
    "delivery" => "पहुंच के भंडार", "log" => "ऐप खाता", "key" => "निजी चाबी",
    "key_body" => "ऐप पासवर्ड लिख के चाबी देखाव। सिरिफ अकेल्ला म।",
    "backup" => "नकल निर्यात",
    "backup_body" => "गुप्त चाबीभंडार बचाथे। दूसर यंत्र म खोले बर पासवर्ड चाही।",
    "password" => "पासवर्ड बदल",
    "password_body" => "अभी के पासवर्ड नेवता के खाना म। नवा नाम के खाना म। पुराना नकल पुराना पासवर्ड रखथे।",
    "about" => "घाल बोल बारे",
    "about_body" => "छोर ले छोर गुप्त संदेश। हर यंत्र अपन बात रखथे।",
    "no_status" => "कोनो हालत नइ हे", "save_backup" => "नकल बचाव",
    "save_backup_body" => "बात ले पहिली गुप्त नकल बचाव। ए अउ पासवर्ड नइ रहे त ए पहिचान लहुटही नइ।",
    "back" => "पाछू", "join_go" => "जुड़", "add_go" => "संपर्क जोड़",
    "add_short" => "जोड़", "toggle" => "रोक बदल", "refresh" => "ताजा",
    "show_key" => "चाबी देखाव", "save" => "नकल बचाव", "change" => "पासवर्ड बदल",
    "save_status" => "हालत बचाव", "speaker" => "स्पिकर", "speaker_off" => "स्पिकर बंद",
    "scan_qr" => "क्यूआर पढ़", "qr_picture" => "क्यूआर फोटू",
    "must_save" => "आघू बढ़े ले पहिली नकल बचाव।",
    "enter_password" => "पहिले ए नकल के पासवर्ड लिख।",
    "choose_file" => "चाबीभंडार के नकल फाइल चुन।",
    "added" => "संपर्क जुड़िस", "saved_prefix" => "बचिस",
];

const LUS: &[(&str, &str)] = sheet![
    "remove" => "Paih rawh",
    "share" => "Sawmna sem rawh", "paste" => "Sawmna dah rawh",
    "paste_body" => "ghalbol:// emaw https://ghalbol.com/connect/ link dah rawh.",
    "add" => "Public key hmanga telh rawh",
    "add_body" => "Guest chuan host public key a dah. Host hian i key a mamawh lo a hmaa.",
    "contacts" => "Mi pawimawh", "none" => "Mi pawimawh a la awm lo", "blocked" => "Kharkhup",
    "blocked_empty" => "Kharkhup a awm lo. List-a mi kharkhup turin public key dah rawh.",
    "delivery" => "Thlenna bung", "log" => "App chhinchhiah", "key" => "Key him",
    "key_body" => "App password ziak la, key en rawh. Hmun himah chauh.",
    "backup" => "Backup chhuah",
    "backup_body" => "Key bung enkawl a vawng. Device dangah hawng turin password a ngai.",
    "password" => "Password thlak rawh",
    "password_body" => "Password tun sawmna ah. Password thar hming ah. Backup hlui chu password hlui a ngai.",
    "about" => "Ghal Bol chungchang",
    "about_body" => "Thuchah enkawl, device tin a thu a vawng.",
    "no_status" => "Status a awm lo", "save_backup" => "Backup vawng rawh",
    "save_backup_body" => "Thuchah hmain backup enkawl vawng rawh. Backup leh password awm lo chuan he identity hi a hawng lo.",
    "back" => "Kir", "join_go" => "Tel rawh", "add_go" => "Mi telh rawh",
    "add_short" => "Telh", "toggle" => "Kharkhup thlak", "refresh" => "Thar rawh",
    "show_key" => "Key entir", "save" => "Backup vawng", "change" => "Password thlak",
    "save_status" => "Status vawng", "speaker" => "Aw chhuahna", "speaker_off" => "Aw chhuahna tit",
    "scan_qr" => "QR en rawh", "qr_picture" => "QR thlalak",
    "must_save" => "Backup vawng hmasa rawh.",
    "enter_password" => "He backup password ziak hmasa rawh.",
    "choose_file" => "Key bung backup file thlang rawh.",
    "added" => "Mi telh a ni", "saved_prefix" => "Vawng a ni",
];

const KHA: &[(&str, &str)] = sheet![
    "remove" => "Pynduh",
    "share" => "Iaiar jingkhot", "paste" => "Pynshong jingkhot",
    "paste_body" => "Pynshong ka link ghalbol:// ne https://ghalbol.com/connect/.",
    "add" => "Pyniasoh da ka kunci public",
    "add_body" => "U guest u buh ia ka kunci public jong u host. U host um donkam shuwa ia ka jong phi.",
    "contacts" => "Ki kontak", "none" => "Khlem kontak shuh", "blocked" => "Lah pynkhang",
    "blocked_empty" => "Khlem ba lah pynkhang. Pynshong ka kunci public ban pynkhang uba don ha ka list.",
    "delivery" => "Ka jaka pynphai", "log" => "Ka kot app", "key" => "Ka kunci private",
    "key_body" => "Thoh ka password app hadien u pyni ia ka kunci. Tang ha ka jaka marwei.",
    "backup" => "Phah backup",
    "backup_body" => "U buh ia ka kot kunci ba lah encrypt. Ha ka device pat donkam password.",
    "password" => "Kyllain password",
    "password_body" => "Password mynta ha ka jaka jingkhot. Ka thymmai ha ka jaka kyrteng. Ki backup barim ki sah bad ka password barim.",
    "about" => "Shaphang Ghal Bol",
    "about_body" => "Jingthoh encrypt na tyllai sha tyllai. Ka device kin buh ia la ka jingiathuhkhana.",
    "no_status" => "Khlem status", "save_backup" => "Buh ia ka backup",
    "save_backup_body" => "Buh ia ka backup encrypt shuwa ban iathuh. Kane ka identity kam wan pat khlem kane bad ka password.",
    "back" => "Phai", "join_go" => "Iasoh", "add_go" => "Pyniasoh kontak",
    "add_short" => "Pyniasoh", "toggle" => "Pynkyllain pynkhang", "refresh" => "Pynthymmai",
    "show_key" => "Pyni kunci", "save" => "Buh backup", "change" => "Kyllain password",
    "save_status" => "Buh status", "speaker" => "Ka speaker", "speaker_off" => "Ka speaker lah kut",
    "scan_qr" => "Pule QR", "qr_picture" => "Ka dur QR",
    "must_save" => "Buh shuwa ia ka backup.",
    "enter_password" => "Thoh shuwa ka password jong kane ka backup.",
    "choose_file" => "Jied ka file backup kot kunci.",
    "added" => "Lah pyniasoh kontak", "saved_prefix" => "Lah buh",
];

const GRT: &[(&str, &str)] = sheet![
    "remove" => "Galna",
    "share" => "Invitation sembo", "paste" => "Invitation donbo",
    "paste_body" => "ghalbol:// ba https://ghalbol.com/connect/ link-ko donbo.",
    "add" => "Public key-chi bakrimbo",
    "add_body" => "Guest host-ni public key-ko done. Host nang·ni key-ko skangon nanga.",
    "contacts" => "Contact-rang", "none" => "Contact dongja", "blocked" => "Jakgiparang",
    "blocked_empty" => "Jakgipa dongja. List-ni mande-ko jakna public key donbo.",
    "delivery" => "Poraiani jok", "log" => "App lekha", "key" => "Private key",
    "key_body" => "App password seokbo, key-ko mesokbo. Tanggipa biaposa.",
    "backup" => "Backup chrokata",
    "backup_body" => "Encrypt gimin key jok-ko done. Gipin device-o ona password nanga.",
    "password" => "Password dakgrikbo",
    "password_body" => "Da·o password invitation-o. Gital password bimung-o. Da·al backup da·al password-ko done.",
    "about" => "Ghal Bol gimin",
    "about_body" => "Encrypt message, device gimik an·tangni golpo-ko done.",
    "no_status" => "Status dongja", "save_backup" => "Backup donebo",
    "save_backup_body" => "Golpo skang encrypt backup donebo. Ian baksa password dongjaode ia identity pil·ja.",
    "back" => "Ja·man", "join_go" => "Bakrimbo", "add_go" => "Contact bakrimbo",
    "add_short" => "Bakrim", "toggle" => "Jakgipa dakgrik", "refresh" => "Gital dakbo",
    "show_key" => "Key mesokbo", "save" => "Backup done", "change" => "Password dakgrik",
    "save_status" => "Status done", "speaker" => "Ku·sik pe", "speaker_off" => "Ku·sik pe bon",
    "scan_qr" => "QR poraibo", "qr_picture" => "QR bimung",
    "must_save" => "Skang backup donebo.",
    "enter_password" => "Skang ia backup-ni password seokbo.",
    "choose_file" => "Key jok backup file sebo.",
    "added" => "Contact bakrimaha", "saved_prefix" => "Donaha",
];

const TRP: &[(&str, &str)] = sheet![
    "remove" => "Koktwi",
    "share" => "Invitation rwkwi", "paste" => "Invitation phunwi",
    "paste_body" => "ghalbol:// ba https://ghalbol.com/connect/ link phunwi.",
    "add" => "Public key bai baksa",
    "add_body" => "Guest host-ni public key rak. Host nangni key koktwkha thangnai.",
    "contacts" => "Contact-rok", "none" => "Contact tongo", "blocked" => "Thangnai",
    "blocked_empty" => "Thangnai tongo. List-ni borok thangna public key phunwi.",
    "delivery" => "Thangnai jok", "log" => "App lekha", "key" => "Private key",
    "key_body" => "App password swi, key nukkwi. Khwnaithani osha.",
    "backup" => "Backup phai",
    "backup_body" => "Encrypt key jok rakwi. Device kwthar o khwnana password nang.",
    "password" => "Password phano",
    "password_body" => "Password tongo invitation o. Password kwthar bimung o. Backup oswi password oswi rak.",
    "about" => "Ghal Bol bising",
    "about_body" => "Encrypt message, device kwbang anokni kothoma rak.",
    "no_status" => "Status tongo", "save_backup" => "Backup rakwi",
    "save_backup_body" => "Kothoma koktwkha encrypt backup rakwi. Backup bai password tongoia identity phan tongo.",
    "back" => "Kok", "join_go" => "Baksa", "add_go" => "Contact baksa",
    "add_short" => "Baksa", "toggle" => "Thangnai phano", "refresh" => "Kwthar",
    "show_key" => "Key nukkwi", "save" => "Backup rak", "change" => "Password phano",
    "save_status" => "Status rak", "speaker" => "Aw pe", "speaker_off" => "Aw pe thang",
    "scan_qr" => "QR porai", "qr_picture" => "QR sak",
    "must_save" => "Koktwkha backup rakwi.",
    "enter_password" => "Koktwkha backup-ni password swi.",
    "choose_file" => "Key jok backup file sal.",
    "added" => "Contact baksaha", "saved_prefix" => "Rakaha",
];

const LEP: &[(&str, &str)] = sheet![
    "remove" => "ཕྱུང",
    "share" => "Invitation zo", "paste" => "Invitation lyo",
    "paste_body" => "ghalbol:// wá https://ghalbol.com/connect/ link lyo.",
    "add" => "Public key nyot",
    "add_body" => "Guest host-m public key zóm. Host nang-m key thóm mányen.",
    "contacts" => "Contact-tsóm", "none" => "Contact mányó", "blocked" => "Chót",
    "blocked_empty" => "Chót mányó. List-m mí chót-ló public key lyo.",
    "delivery" => "Thóm jok", "log" => "App lekha", "key" => "Private key",
    "key_body" => "App password brí, key tón. Róng thám-ló.",
    "backup" => "Backup phyó",
    "backup_body" => "Encrypt key jok zóm. Device nyím-ló khyóna password nyen.",
    "password" => "Password phyó",
    "password_body" => "Password thóm invitation-ló. Password thom bimung-ló. Backup nyim password nyim zóm.",
    "about" => "Ghal Bol tham",
    "about_body" => "Encrypt message, device tsóm áre kathóm zóm.",
    "no_status" => "Status mányó", "save_backup" => "Backup zóm",
    "save_backup_body" => "Kathóm thóm encrypt backup zóm. Backup wá password mányó-re identity phyó mányen.",
    "back" => "Nyim", "join_go" => "Nyot", "add_go" => "Contact nyot",
    "add_short" => "Nyot", "toggle" => "Chót phyó", "refresh" => "Thom",
    "show_key" => "Key tón", "save" => "Backup zóm", "change" => "Password phyó",
    "save_status" => "Status zóm", "speaker" => "Aw pe", "speaker_off" => "Aw pe chót",
    "scan_qr" => "QR pó", "qr_picture" => "QR sak",
    "must_save" => "Thóm backup zóm.",
    "enter_password" => "Thóm backup-m password brí.",
    "choose_file" => "Key jok backup file lyo.",
    "added" => "Contact nyotá", "saved_prefix" => "Zómá",
];
